import { MissingPieceTeamData } from "./missing-data";

export const MISSING_PIECE_EXPANSION_1: MissingPieceTeamData[] = [
  {
    pays: "France 1998 (Légendes)",
    drapeau: "🇫🇷",
    formation: "4-3-2-1",
    joueurs: [
      { nom: "Barthez", prenom: "Fabien", poste: "GK", numero: 16, posX: 50, posY: 90 },
      { nom: "Thuram", prenom: "Lilian", poste: "DEF", numero: 15, posX: 85, posY: 75 },
      { nom: "Blanc", prenom: "Laurent", poste: "DEF", numero: 5, posX: 62, posY: 75 },
      { nom: "Desailly", prenom: "Marcel", poste: "DEF", numero: 8, posX: 38, posY: 75 },
      { nom: "Lizarazu", prenom: "Bixente", poste: "DEF", numero: 3, posX: 15, posY: 75 },
      { nom: "Deschamps", prenom: "Didier", poste: "MID", numero: 7, posX: 50, posY: 58 },
      { nom: "Karembeu", prenom: "Christian", poste: "MID", numero: 19, posX: 75, posY: 55 },
      { nom: "Petit", prenom: "Emmanuel", poste: "MID", numero: 17, posX: 25, posY: 55 },
      { nom: "Zidane", prenom: "Zinédine", poste: "MID", numero: 10, posX: 65, posY: 38 },
      { nom: "Djorkaeff", prenom: "Youri", poste: "FWD", numero: 6, posX: 35, posY: 38 },
      { nom: "Guivarc'h", prenom: "Stéphane", poste: "FWD", numero: 9, posX: 50, posY: 20 },
    ],
    joueurManquantIndex: 8, // Zidane
  },
  {
    pays: "Brésil 2002 (Légendes)",
    drapeau: "🇧🇷",
    formation: "3-4-2-1",
    joueurs: [
      { nom: "Marcos", prenom: "", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Lúcio", prenom: "", poste: "DEF", numero: 3, posX: 75, posY: 75 },
      { nom: "Edmílson", prenom: "", poste: "DEF", numero: 5, posX: 50, posY: 75 },
      { nom: "Roque Júnior", prenom: "", poste: "DEF", numero: 4, posX: 25, posY: 75 },
      { nom: "Cafu", prenom: "", poste: "MID", numero: 2, posX: 85, posY: 55 },
      { nom: "Kléberson", prenom: "", poste: "MID", numero: 15, posX: 65, posY: 55 },
      { nom: "Gilberto Silva", prenom: "", poste: "MID", numero: 8, posX: 35, posY: 55 },
      { nom: "Roberto Carlos", prenom: "", poste: "MID", numero: 6, posX: 15, posY: 55 },
      { nom: "Ronaldinho", prenom: "", poste: "FWD", numero: 11, posX: 30, posY: 35 },
      { nom: "Rivaldo", prenom: "", poste: "FWD", numero: 10, posX: 70, posY: 35 },
      { nom: "Ronaldo", prenom: "", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 10, // Ronaldo
  },
  {
    pays: "Italie 2006 (Légendes)",
    drapeau: "🇮🇹",
    formation: "4-4-1-1",
    joueurs: [
      { nom: "Buffon", prenom: "Gianluigi", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Zambrotta", prenom: "Gianluca", poste: "DEF", numero: 19, posX: 85, posY: 72 },
      { nom: "Cannavaro", prenom: "Fabio", poste: "DEF", numero: 5, posX: 62, posY: 75 },
      { nom: "Materazzi", prenom: "Marco", poste: "DEF", numero: 23, posX: 38, posY: 75 },
      { nom: "Grosso", prenom: "Fabio", poste: "DEF", numero: 3, posX: 15, posY: 72 },
      { nom: "Camoranesi", prenom: "Mauro", poste: "MID", numero: 16, posX: 80, posY: 52 },
      { nom: "Gattuso", prenom: "Gennaro", poste: "MID", numero: 8, posX: 60, posY: 55 },
      { nom: "Pirlo", prenom: "Andrea", poste: "MID", numero: 21, posX: 40, posY: 55 },
      { nom: "Perrotta", prenom: "Simone", poste: "MID", numero: 20, posX: 20, posY: 52 },
      { nom: "Totti", prenom: "Francesco", poste: "MID", numero: 10, posX: 50, posY: 38 },
      { nom: "Toni", prenom: "Luca", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 2, // Cannavaro
  },
  {
    pays: "Espagne 2010 (Légendes)",
    drapeau: "🇪🇸",
    formation: "4-2-3-1",
    joueurs: [
      { nom: "Casillas", prenom: "Iker", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Ramos", prenom: "Sergio", poste: "DEF", numero: 15, posX: 85, posY: 72 },
      { nom: "Piqué", prenom: "Gerard", poste: "DEF", numero: 3, posX: 62, posY: 75 },
      { nom: "Puyol", prenom: "Carles", poste: "DEF", numero: 5, posX: 38, posY: 75 },
      { nom: "Capdevila", prenom: "Joan", poste: "DEF", numero: 11, posX: 15, posY: 72 },
      { nom: "Busquets", prenom: "Sergio", poste: "MID", numero: 16, posX: 50, posY: 58 },
      { nom: "Alonso", prenom: "Xabi", poste: "MID", numero: 14, posX: 65, posY: 52 },
      { nom: "Xavi", prenom: "", poste: "MID", numero: 8, posX: 35, posY: 52 },
      { nom: "Iniesta", prenom: "Andrés", poste: "MID", numero: 6, posX: 20, posY: 35 },
      { nom: "Pedro", prenom: "", poste: "FWD", numero: 18, posX: 80, posY: 35 },
      { nom: "Villa", prenom: "David", poste: "FWD", numero: 7, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 8, // Iniesta
  },
  {
    pays: "Allemagne 2014 (Légendes)",
    drapeau: "🇩🇪",
    formation: "4-2-3-1",
    joueurs: [
      { nom: "Neuer", prenom: "Manuel", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Lahm", prenom: "Philipp", poste: "DEF", numero: 16, posX: 85, posY: 72 },
      { nom: "Boateng", prenom: "Jérôme", poste: "DEF", numero: 20, posX: 62, posY: 75 },
      { nom: "Hummels", prenom: "Mats", poste: "DEF", numero: 5, posX: 38, posY: 75 },
      { nom: "Höwedes", prenom: "Benedikt", poste: "DEF", numero: 4, posX: 15, posY: 72 },
      { nom: "Khedira", prenom: "Sami", poste: "MID", numero: 6, posX: 65, posY: 55 },
      { nom: "Schweinsteiger", prenom: "Bastian", poste: "MID", numero: 7, posX: 35, posY: 55 },
      { nom: "Müller", prenom: "Thomas", poste: "FWD", numero: 13, posX: 80, posY: 35 },
      { nom: "Kroos", prenom: "Toni", poste: "MID", numero: 18, posX: 50, posY: 38 },
      { nom: "Özil", prenom: "Mesut", poste: "MID", numero: 8, posX: 20, posY: 35 },
      { nom: "Klose", prenom: "Miroslav", poste: "FWD", numero: 11, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 10, // Klose
  },
  {
    pays: "France 2018 (Légendes)",
    drapeau: "🇫🇷",
    formation: "4-2-3-1",
    joueurs: [
      { nom: "Lloris", prenom: "Hugo", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Pavard", prenom: "Benjamin", poste: "DEF", numero: 2, posX: 85, posY: 72 },
      { nom: "Varane", prenom: "Raphaël", poste: "DEF", numero: 4, posX: 62, posY: 75 },
      { nom: "Umtiti", prenom: "Samuel", poste: "DEF", numero: 5, posX: 38, posY: 75 },
      { nom: "Hernández", prenom: "Lucas", poste: "DEF", numero: 21, posX: 15, posY: 72 },
      { nom: "Kanté", prenom: "N'Golo", poste: "MID", numero: 13, posX: 65, posY: 55 },
      { nom: "Pogba", prenom: "Paul", poste: "MID", numero: 6, posX: 35, posY: 55 },
      { nom: "Mbappé", prenom: "Kylian", poste: "FWD", numero: 10, posX: 80, posY: 35 },
      { nom: "Griezmann", prenom: "Antoine", poste: "MID", numero: 7, posX: 50, posY: 38 },
      { nom: "Matuidi", prenom: "Blaise", poste: "MID", numero: 14, posX: 20, posY: 35 },
      { nom: "Giroud", prenom: "Olivier", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 6, // Pogba
  },
  {
    pays: "Argentine 1986 (Légendes)",
    drapeau: "🇦🇷",
    formation: "3-5-2",
    joueurs: [
      { nom: "Pumpido", prenom: "Nery", poste: "GK", numero: 18, posX: 50, posY: 90 },
      { nom: "Cuciuffo", prenom: "José Luis", poste: "DEF", numero: 9, posX: 75, posY: 75 },
      { nom: "Brown", prenom: "José Luis", poste: "DEF", numero: 5, posX: 50, posY: 75 },
      { nom: "Ruggeri", prenom: "Oscar", poste: "DEF", numero: 19, posX: 25, posY: 75 },
      { nom: "Giusti", prenom: "Ricardo", poste: "MID", numero: 14, posX: 85, posY: 55 },
      { nom: "Burruchaga", prenom: "Jorge", poste: "MID", numero: 7, posX: 65, posY: 50 },
      { nom: "Batista", prenom: "Sergio", poste: "MID", numero: 2, posX: 50, posY: 60 },
      { nom: "Enrique", prenom: "Héctor", poste: "MID", numero: 12, posX: 35, posY: 50 },
      { nom: "Olarticoechea", prenom: "Julio", poste: "MID", numero: 16, posX: 15, posY: 55 },
      { nom: "Maradona", prenom: "Diego", poste: "FWD", numero: 10, posX: 50, posY: 35 },
      { nom: "Valdano", prenom: "Jorge", poste: "FWD", numero: 11, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 9, // Maradona
  },
  {
    pays: "Croatie 2018 (Légendes)",
    drapeau: "🇭🇷",
    formation: "4-3-3",
    joueurs: [
      { nom: "Subašić", prenom: "Danijel", poste: "GK", numero: 23, posX: 50, posY: 90 },
      { nom: "Vrsaljko", prenom: "Šime", poste: "DEF", numero: 2, posX: 85, posY: 72 },
      { nom: "Lovren", prenom: "Dejan", poste: "DEF", numero: 6, posX: 62, posY: 75 },
      { nom: "Vida", prenom: "Domagoj", poste: "DEF", numero: 21, posX: 38, posY: 75 },
      { nom: "Strinić", prenom: "Ivan", poste: "DEF", numero: 3, posX: 15, posY: 72 },
      { nom: "Brozović", prenom: "Marcelo", poste: "MID", numero: 11, posX: 50, posY: 58 },
      { nom: "Modrić", prenom: "Luka", poste: "MID", numero: 10, posX: 65, posY: 52 },
      { nom: "Rakitić", prenom: "Ivan", poste: "MID", numero: 7, posX: 35, posY: 52 },
      { nom: "Rebić", prenom: "Ante", poste: "FWD", numero: 18, posX: 80, posY: 28 },
      { nom: "Mandžukić", prenom: "Mario", poste: "FWD", numero: 17, posX: 50, posY: 22 },
      { nom: "Perišić", prenom: "Ivan", poste: "FWD", numero: 4, posX: 20, posY: 28 },
    ],
    joueurManquantIndex: 6, // Modric
  },
  {
    pays: "Sénégal 2002 (Légendes)",
    drapeau: "🇸🇳",
    formation: "4-1-4-1",
    joueurs: [
      { nom: "Sylva", prenom: "Tony", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Coly", prenom: "Ferdinand", poste: "DEF", numero: 17, posX: 85, posY: 72 },
      { nom: "Diatta", prenom: "Lamine", poste: "DEF", numero: 13, posX: 62, posY: 75 },
      { nom: "Diop", prenom: "Pape Malick", poste: "DEF", numero: 4, posX: 38, posY: 75 },
      { nom: "Daf", prenom: "Omar", poste: "DEF", numero: 2, posX: 15, posY: 72 },
      { nom: "Cissé", prenom: "Aliou", poste: "MID", numero: 6, posX: 50, posY: 58 },
      { nom: "Diouf", prenom: "El Hadji", poste: "FWD", numero: 11, posX: 80, posY: 40 },
      { nom: "Diop", prenom: "Papa Bouba", poste: "MID", numero: 19, posX: 65, posY: 48 },
      { nom: "Fadiga", prenom: "Khalilou", poste: "MID", numero: 10, posX: 35, posY: 48 },
      { nom: "N'Diaye", prenom: "Moussa", poste: "MID", numero: 14, posX: 20, posY: 40 },
      { nom: "Camara", prenom: "Henri", poste: "FWD", numero: 7, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 6, // Diouf
  },
  {
    pays: "Brésil 1970 (Légendes)",
    drapeau: "🇧🇷",
    formation: "4-2-4",
    joueurs: [
      { nom: "Félix", prenom: "", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Carlos Alberto", prenom: "", poste: "DEF", numero: 4, posX: 85, posY: 72 },
      { nom: "Brito", prenom: "", poste: "DEF", numero: 2, posX: 62, posY: 75 },
      { nom: "Piazza", prenom: "", poste: "DEF", numero: 3, posX: 38, posY: 75 },
      { nom: "Everaldo", prenom: "", poste: "DEF", numero: 16, posX: 15, posY: 72 },
      { nom: "Clodoaldo", prenom: "", poste: "MID", numero: 5, posX: 62, posY: 50 },
      { nom: "Gérson", prenom: "", poste: "MID", numero: 8, posX: 38, posY: 50 },
      { nom: "Jairzinho", prenom: "", poste: "FWD", numero: 7, posX: 85, posY: 28 },
      { nom: "Tostão", prenom: "", poste: "FWD", numero: 9, posX: 60, posY: 22 },
      { nom: "Pelé", prenom: "Edson", poste: "FWD", numero: 10, posX: 40, posY: 22 },
      { nom: "Rivellino", prenom: "", poste: "FWD", numero: 11, posX: 15, posY: 28 },
    ],
    joueurManquantIndex: 9, // Pelé
  },
  {
    pays: "Uruguay 2010 (Légendes)",
    drapeau: "🇺🇾",
    formation: "4-3-3",
    joueurs: [
      { nom: "Muslera", prenom: "Fernando", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "M. Pereira", prenom: "Maxi", poste: "DEF", numero: 16, posX: 85, posY: 75 },
      { nom: "Lugano", prenom: "Diego", poste: "DEF", numero: 2, posX: 62, posY: 78 },
      { nom: "Godín", prenom: "Diego", poste: "DEF", numero: 3, posX: 38, posY: 78 },
      { nom: "Fucile", prenom: "Jorge", poste: "DEF", numero: 4, posX: 15, posY: 75 },
      { nom: "Pérez", prenom: "Diego", poste: "MID", numero: 15, posX: 75, posY: 58 },
      { nom: "Arévalo", prenom: "Egidio", poste: "MID", numero: 17, posX: 50, posY: 62 },
      { nom: "A. Fernández", prenom: "Álvaro", poste: "MID", numero: 20, posX: 25, posY: 58 },
      { nom: "Cavani", prenom: "Edinson", poste: "FWD", numero: 7, posX: 80, posY: 35 },
      { nom: "Suárez", prenom: "Luis", poste: "FWD", numero: 9, posX: 50, posY: 22 },
      { nom: "Forlán", prenom: "Diego", poste: "FWD", numero: 10, posX: 20, posY: 35 },
    ],
    joueurManquantIndex: 10, // Forlán
  },
  {
    pays: "Colombie 2014",
    drapeau: "🇨🇴",
    formation: "4-2-3-1",
    joueurs: [
      { nom: "Ospina", prenom: "David", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Zúñiga", prenom: "Camilo", poste: "DEF", numero: 18, posX: 85, posY: 72 },
      { nom: "Zapata", prenom: "Cristián", poste: "DEF", numero: 2, posX: 62, posY: 75 },
      { nom: "Yepes", prenom: "Mario", poste: "DEF", numero: 3, posX: 38, posY: 75 },
      { nom: "Armero", prenom: "Pablo", poste: "DEF", numero: 7, posX: 15, posY: 72 },
      { nom: "Sánchez", prenom: "Carlos", poste: "MID", numero: 6, posX: 65, posY: 55 },
      { nom: "Aguilar", prenom: "Abel", poste: "MID", numero: 8, posX: 35, posY: 55 },
      { nom: "Cuadrado", prenom: "Juan", poste: "MID", numero: 11, posX: 80, posY: 38 },
      { nom: "James", prenom: "Rodríguez", poste: "MID", numero: 10, posX: 50, posY: 35 },
      { nom: "Ibarbo", prenom: "Víctor", poste: "FWD", numero: 14, posX: 20, posY: 38 },
      { nom: "Teófilo", prenom: "Gutiérrez", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 8, // James
  },
  {
    pays: "Japon 2022",
    drapeau: "🇯🇵",
    formation: "3-4-3",
    joueurs: [
      { nom: "Gonda", prenom: "Shūichi", poste: "GK", numero: 12, posX: 50, posY: 90 },
      { nom: "Itakura", prenom: "Ko", poste: "DEF", numero: 4, posX: 75, posY: 75 },
      { nom: "Yoshida", prenom: "Maya", poste: "DEF", numero: 22, posX: 50, posY: 75 },
      { nom: "Taniguchi", prenom: "Shogo", poste: "DEF", numero: 3, posX: 25, posY: 75 },
      { nom: "Ito", prenom: "Junya", poste: "MID", numero: 14, posX: 88, posY: 55 },
      { nom: "Endo", prenom: "Wataru", poste: "MID", numero: 6, posX: 65, posY: 55 },
      { nom: "Morita", prenom: "Hidemasa", poste: "MID", numero: 13, posX: 35, posY: 55 },
      { nom: "Nagatomo", prenom: "Yuto", poste: "MID", numero: 5, posX: 12, posY: 55 },
      { nom: "Doan", prenom: "Ritsu", poste: "FWD", numero: 8, posX: 75, posY: 28 },
      { nom: "Maeda", prenom: "Daizen", poste: "FWD", numero: 25, posX: 50, posY: 22 },
      { nom: "Kamada", prenom: "Daichi", poste: "FWD", numero: 15, posX: 25, posY: 28 },
    ],
    joueurManquantIndex: 4, // Ito (Junya)
  },
  {
    pays: "Corée du Sud 2002 (Légendes)",
    drapeau: "🇰🇷",
    formation: "3-4-3",
    joueurs: [
      { nom: "Lee", prenom: "Woon-jae", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Choi", prenom: "Jin-cheul", poste: "DEF", numero: 4, posX: 75, posY: 75 },
      { nom: "Hong", prenom: "Myung-bo", poste: "DEF", numero: 20, posX: 50, posY: 75 },
      { nom: "Kim", prenom: "Tae-young", poste: "DEF", numero: 7, posX: 25, posY: 75 },
      { nom: "Song", prenom: "Chong-gug", poste: "MID", numero: 22, posX: 88, posY: 55 },
      { nom: "Kim", prenom: "Nam-il", poste: "MID", numero: 5, posX: 65, posY: 55 },
      { nom: "Yoo", prenom: "Sang-chul", poste: "MID", numero: 21, posX: 35, posY: 55 },
      { nom: "Lee", prenom: "Young-pyo", poste: "MID", numero: 10, posX: 12, posY: 55 },
      { nom: "Park", prenom: "Ji-sung", poste: "FWD", numero: 21, posX: 75, posY: 28 },
      { nom: "Ahn", prenom: "Jung-hwan", poste: "FWD", numero: 19, posX: 50, posY: 22 },
      { nom: "Seol", prenom: "Ki-hyeon", poste: "FWD", numero: 9, posX: 25, posY: 28 },
    ],
    joueurManquantIndex: 8, // Park Ji-Sung
  },
  {
    pays: "Nigeria 1994 (Légendes)",
    drapeau: "🇳🇬",
    formation: "4-4-2",
    joueurs: [
      { nom: "Rufai", prenom: "Peter", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Eguavoen", prenom: "Augustine", poste: "DEF", numero: 2, posX: 85, posY: 72 },
      { nom: "Okechukwu", prenom: "Uche", poste: "DEF", numero: 5, posX: 62, posY: 75 },
      { nom: "Nwanu", prenom: "Chidi", poste: "DEF", numero: 6, posX: 38, posY: 75 },
      { nom: "Emenalo", prenom: "Michael", poste: "DEF", numero: 19, posX: 15, posY: 72 },
      { nom: "Finidi", prenom: "George", poste: "MID", numero: 7, posX: 85, posY: 50 },
      { nom: "Oliseh", prenom: "Sunday", poste: "MID", numero: 15, posX: 65, posY: 55 },
      { nom: "Okocha", prenom: "Jay-Jay", poste: "MID", numero: 10, posX: 35, posY: 55 },
      { nom: "Amuneke", prenom: "Emmanuel", poste: "MID", numero: 11, posX: 15, posY: 50 },
      { nom: "Amokachi", prenom: "Daniel", poste: "FWD", numero: 14, posX: 60, posY: 22 },
      { nom: "Yekini", prenom: "Rashidi", poste: "FWD", numero: 9, posX: 40, posY: 22 },
    ],
    joueurManquantIndex: 7, // Okocha
  }
];
