import { MissingPieceTeamData } from "./missing-data";

export const MISSING_PIECE_EXPANSION_2: MissingPieceTeamData[] = [
  {
    pays: "Cameroun 1990 (Légendes)",
    drapeau: "🇨🇲",
    formation: "4-4-2",
    joueurs: [
      { nom: "N'Kono", prenom: "Thomas", poste: "GK", numero: 16, posX: 50, posY: 90 },
      { nom: "Ebongué", prenom: "Ernest", poste: "DEF", numero: 2, posX: 85, posY: 72 },
      { nom: "Kundé", prenom: "Emmanuel", poste: "DEF", numero: 6, posX: 62, posY: 75 },
      { nom: "Ndip", prenom: "Victor", poste: "DEF", numero: 5, posX: 38, posY: 75 },
      { nom: "Onana", prenom: "Jules", poste: "DEF", numero: 3, posX: 15, posY: 72 },
      { nom: "Makanaky", prenom: "Cyrille", poste: "MID", numero: 8, posX: 85, posY: 50 },
      { nom: "M'Fédé", prenom: "Louis-Paul", poste: "MID", numero: 10, posX: 65, posY: 55 },
      { nom: "Kana-Biyik", prenom: "André", poste: "MID", numero: 14, posX: 35, posY: 55 },
      { nom: "Boubou", prenom: "Emile", poste: "MID", numero: 20, posX: 15, posY: 50 },
      { nom: "Omam-Biyik", prenom: "François", poste: "FWD", numero: 7, posX: 60, posY: 22 },
      { nom: "Milla", prenom: "Roger", poste: "FWD", numero: 9, posX: 40, posY: 22 },
    ],
    joueurManquantIndex: 10, // Roger Milla
  },
  {
    pays: "Belgique 2018",
    drapeau: "🇧🇪",
    formation: "3-4-2-1",
    joueurs: [
      { nom: "Courtois", prenom: "Thibaut", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Alderweireld", prenom: "Toby", poste: "DEF", numero: 2, posX: 75, posY: 75 },
      { nom: "Kompany", prenom: "Vincent", poste: "DEF", numero: 4, posX: 50, posY: 75 },
      { nom: "Vertonghen", prenom: "Jan", poste: "DEF", numero: 5, posX: 25, posY: 75 },
      { nom: "Meunier", prenom: "Thomas", poste: "MID", numero: 15, posX: 88, posY: 55 },
      { nom: "Fellaini", prenom: "Marouane", poste: "MID", numero: 8, posX: 65, posY: 55 },
      { nom: "Witsel", prenom: "Axel", poste: "MID", numero: 6, posX: 35, posY: 55 },
      { nom: "Chadli", prenom: "Nacer", poste: "MID", numero: 22, posX: 12, posY: 55 },
      { nom: "De Bruyne", prenom: "Kevin", poste: "FWD", numero: 7, posX: 75, posY: 35 },
      { nom: "Hazard", prenom: "Eden", poste: "FWD", numero: 10, posX: 25, posY: 35 },
      { nom: "Lukaku", prenom: "Romelu", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 9, // Eden Hazard
  },
  {
    pays: "Italie 1982 (Légendes)",
    drapeau: "🇮🇹",
    formation: "3-5-2",
    joueurs: [
      { nom: "Zoff", prenom: "Dino", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Scirea", prenom: "Gaetano", poste: "DEF", numero: 7, posX: 50, posY: 75 },
      { nom: "Gentile", prenom: "Claudio", poste: "DEF", numero: 5, posX: 75, posY: 75 },
      { nom: "Collovati", prenom: "Fulvio", poste: "DEF", numero: 4, posX: 25, posY: 75 },
      { nom: "Bergomi", prenom: "Giuseppe", poste: "MID", numero: 3, posX: 85, posY: 55 },
      { nom: "Tardelli", prenom: "Marco", poste: "MID", numero: 14, posX: 65, posY: 50 },
      { nom: "Oriali", prenom: "Gabriele", poste: "MID", numero: 13, posX: 35, posY: 50 },
      { nom: "Antognoni", prenom: "Giancarlo", poste: "MID", numero: 9, posX: 50, posY: 40 },
      { nom: "Cabrini", prenom: "Antonio", poste: "MID", numero: 6, posX: 15, posY: 55 },
      { nom: "Graziani", prenom: "Francesco", poste: "FWD", numero: 19, posX: 70, posY: 22 },
      { nom: "Rossi", prenom: "Paolo", poste: "FWD", numero: 20, posX: 30, posY: 22 },
    ],
    joueurManquantIndex: 10, // Paolo Rossi
  },
  {
    pays: "Pays-Bas 2014",
    drapeau: "🇳🇱",
    formation: "3-5-2",
    joueurs: [
      { nom: "Cillessen", prenom: "Jasper", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "De Vrij", prenom: "Stefan", poste: "DEF", numero: 3, posX: 75, posY: 75 },
      { nom: "Vlaar", prenom: "Ron", poste: "DEF", numero: 2, posX: 50, posY: 75 },
      { nom: "Martins Indi", prenom: "Bruno", poste: "DEF", numero: 4, posX: 25, posY: 75 },
      { nom: "Kuyt", prenom: "Dirk", poste: "MID", numero: 15, posX: 85, posY: 55 },
      { nom: "Wijnaldum", prenom: "Giorginio", poste: "MID", numero: 20, posX: 65, posY: 50 },
      { nom: "Sneijder", prenom: "Wesley", poste: "MID", numero: 10, posX: 50, posY: 40 },
      { nom: "De Jong", prenom: "Nigel", poste: "MID", numero: 6, posX: 35, posY: 50 },
      { nom: "Blind", prenom: "Daley", poste: "MID", numero: 5, posX: 15, posY: 55 },
      { nom: "Robben", prenom: "Arjen", poste: "FWD", numero: 11, posX: 70, posY: 22 },
      { nom: "Van Persie", prenom: "Robin", poste: "FWD", numero: 9, posX: 30, posY: 22 },
    ],
    joueurManquantIndex: 9, // Arjen Robben
  },
  {
    pays: "Allemagne 1990 (Légendes)",
    drapeau: "🇩🇪",
    formation: "3-5-2",
    joueurs: [
      { nom: "Illgner", prenom: "Bodo", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Buchwald", prenom: "Guido", poste: "DEF", numero: 6, posX: 75, posY: 75 },
      { nom: "Augenthaler", prenom: "Klaus", poste: "DEF", numero: 5, posX: 50, posY: 75 },
      { nom: "Kohler", prenom: "Jürgen", poste: "DEF", numero: 4, posX: 25, posY: 75 },
      { nom: "Reuter", prenom: "Stefan", poste: "MID", numero: 2, posX: 85, posY: 55 },
      { nom: "Häßler", prenom: "Thomas", poste: "MID", numero: 8, posX: 65, posY: 50 },
      { nom: "Matthäus", prenom: "Lothar", poste: "MID", numero: 10, posX: 50, posY: 45 },
      { nom: "Littbarski", prenom: "Pierre", poste: "MID", numero: 7, posX: 35, posY: 50 },
      { nom: "Brehme", prenom: "Andreas", poste: "MID", numero: 3, posX: 15, posY: 55 },
      { nom: "Klinsmann", prenom: "Jürgen", poste: "FWD", numero: 18, posX: 70, posY: 22 },
      { nom: "Völler", prenom: "Rudi", poste: "FWD", numero: 9, posX: 30, posY: 22 },
    ],
    joueurManquantIndex: 6, // Lothar Matthäus
  },
  {
    pays: "Brésil 1958 (Légendes)",
    drapeau: "🇧🇷",
    formation: "4-2-4",
    joueurs: [
      { nom: "Gilmar", prenom: "", poste: "GK", numero: 3, posX: 50, posY: 90 },
      { nom: "Djalma Santos", prenom: "", poste: "DEF", numero: 4, posX: 85, posY: 72 },
      { nom: "Bellini", prenom: "", poste: "DEF", numero: 2, posX: 62, posY: 75 },
      { nom: "Orlando", prenom: "", poste: "DEF", numero: 15, posX: 38, posY: 75 },
      { nom: "Nílton Santos", prenom: "", poste: "DEF", numero: 12, posX: 15, posY: 72 },
      { nom: "Zito", prenom: "", poste: "MID", numero: 19, posX: 62, posY: 50 },
      { nom: "Didi", prenom: "", poste: "MID", numero: 6, posX: 38, posY: 50 },
      { nom: "Garrincha", prenom: "", poste: "FWD", numero: 11, posX: 85, posY: 28 },
      { nom: "Vavá", prenom: "", poste: "FWD", numero: 20, posX: 60, posY: 22 },
      { nom: "Pelé", prenom: "Edson", poste: "FWD", numero: 10, posX: 40, posY: 22 },
      { nom: "Zagallo", prenom: "", poste: "FWD", numero: 7, posX: 15, posY: 28 },
    ],
    joueurManquantIndex: 9, // Pelé
  },
  {
    pays: "Angleterre 1966 (Légendes)",
    drapeau: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    formation: "4-1-3-2",
    joueurs: [
      { nom: "Banks", prenom: "Gordon", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Cohen", prenom: "George", poste: "DEF", numero: 2, posX: 85, posY: 72 },
      { nom: "Charlton", prenom: "Jack", poste: "DEF", numero: 5, posX: 62, posY: 75 },
      { nom: "Moore", prenom: "Bobby", poste: "DEF", numero: 6, posX: 38, posY: 75 },
      { nom: "Wilson", prenom: "Ray", poste: "DEF", numero: 3, posX: 15, posY: 72 },
      { nom: "Stiles", prenom: "Nobby", poste: "MID", numero: 4, posX: 50, posY: 65 },
      { nom: "Ball", prenom: "Alan", poste: "MID", numero: 7, posX: 80, posY: 45 },
      { nom: "Charlton", prenom: "Bobby", poste: "MID", numero: 9, posX: 50, posY: 40 },
      { nom: "Peters", prenom: "Martin", poste: "MID", numero: 16, posX: 20, posY: 45 },
      { nom: "Hurst", prenom: "Geoff", poste: "FWD", numero: 10, posX: 60, posY: 22 },
      { nom: "Hunt", prenom: "Roger", poste: "FWD", numero: 21, posX: 40, posY: 22 },
    ],
    joueurManquantIndex: 7, // Bobby Charlton
  },
  {
    pays: "Argentine 1978 (Légendes)",
    drapeau: "🇦🇷",
    formation: "4-3-3",
    joueurs: [
      { nom: "Fillol", prenom: "Ubaldo", poste: "GK", numero: 5, posX: 50, posY: 90 },
      { nom: "Olguín", prenom: "Jorge", poste: "DEF", numero: 15, posX: 85, posY: 72 },
      { nom: "Galván", prenom: "Luis", poste: "DEF", numero: 7, posX: 62, posY: 75 },
      { nom: "Passarella", prenom: "Daniel", poste: "DEF", numero: 19, posX: 38, posY: 75 },
      { nom: "Tarantini", prenom: "Alberto", poste: "DEF", numero: 20, posX: 15, posY: 72 },
      { nom: "Ardiles", prenom: "Osvaldo", poste: "MID", numero: 2, posX: 70, posY: 52 },
      { nom: "Gallego", prenom: "Américo", poste: "MID", numero: 6, posX: 50, posY: 55 },
      { nom: "Kempes", prenom: "Mario", poste: "MID", numero: 10, posX: 30, posY: 52 },
      { nom: "Bertoni", prenom: "Daniel", poste: "FWD", numero: 4, posX: 80, posY: 28 },
      { nom: "Luque", prenom: "Leopoldo", poste: "FWD", numero: 14, posX: 50, posY: 22 },
      { nom: "Ortiz", prenom: "Oscar", poste: "FWD", numero: 16, posX: 20, posY: 28 },
    ],
    joueurManquantIndex: 7, // Mario Kempes
  },
  {
    pays: "Ghana 2010",
    drapeau: "🇬🇭",
    formation: "4-2-3-1",
    joueurs: [
      { nom: "Kingson", prenom: "Richard", poste: "GK", numero: 22, posX: 50, posY: 90 },
      { nom: "Paintsil", prenom: "John", poste: "DEF", numero: 4, posX: 85, posY: 72 },
      { nom: "Mensah", prenom: "John", poste: "DEF", numero: 5, posX: 62, posY: 75 },
      { nom: "Vorsah", prenom: "Isaac", poste: "DEF", numero: 15, posX: 38, posY: 75 },
      { nom: "Sarpei", prenom: "Hans", poste: "DEF", numero: 2, posX: 15, posY: 72 },
      { nom: "Annan", prenom: "Anthony", poste: "MID", numero: 6, posX: 65, posY: 55 },
      { nom: "Boateng", prenom: "Kevin-Prince", poste: "MID", numero: 23, posX: 35, posY: 55 },
      { nom: "Inkoom", prenom: "Samuel", poste: "MID", numero: 7, posX: 80, posY: 35 },
      { nom: "Asamoah", prenom: "Kwadwo", poste: "MID", numero: 21, posX: 50, posY: 38 },
      { nom: "Muntari", prenom: "Sulley", poste: "MID", numero: 11, posX: 20, posY: 35 },
      { nom: "Gyan", prenom: "Asamoah", poste: "FWD", numero: 3, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 10, // Asamoah Gyan
  },
  {
    pays: "Costa Rica 2014",
    drapeau: "🇨🇷",
    formation: "5-4-1",
    joueurs: [
      { nom: "Navas", prenom: "Keylor", poste: "GK", numero: 1, posX: 50, posY: 90 },
      { nom: "Gamboa", prenom: "Cristian", poste: "DEF", numero: 16, posX: 88, posY: 65 },
      { nom: "Duarte", prenom: "Óscar", poste: "DEF", numero: 6, posX: 70, posY: 75 },
      { nom: "González", prenom: "Giancarlo", poste: "DEF", numero: 3, posX: 50, posY: 75 },
      { nom: "Umaña", prenom: "Michael", poste: "DEF", numero: 4, posX: 30, posY: 75 },
      { nom: "Díaz", prenom: "Júnior", poste: "DEF", numero: 15, posX: 12, posY: 65 },
      { nom: "Ruiz", prenom: "Bryan", poste: "MID", numero: 10, posX: 75, posY: 45 },
      { nom: "Borges", prenom: "Celso", poste: "MID", numero: 5, posX: 60, posY: 55 },
      { nom: "Tejeda", prenom: "Yeltsin", poste: "MID", numero: 17, posX: 40, posY: 55 },
      { nom: "Bolaños", prenom: "Christian", poste: "MID", numero: 7, posX: 25, posY: 45 },
      { nom: "Campbell", prenom: "Joel", poste: "FWD", numero: 9, posX: 50, posY: 22 },
    ],
    joueurManquantIndex: 0, // Keylor Navas (Gardien de but ! Piège)
  }
];
