/**
 * FootQuest - Additional WC2026 Teams (36 teams)
 * Combined with the 12 in scout-data.ts = 48 total
 *
 * VERIFIED list from FIFA/Wikipedia as of April 2026.
 * Italy, Nigeria, Ghana, Cameroun, Chile, Pérou are NOT qualified.
 */
import type { ScoutTeamData } from "./scout-data";

const P = { GK: "GK", DEF: "DEF", MID: "MID", FWD: "FWD" } as const;
const pos = { gk:{posX:50,posY:90}, rb:{posX:85,posY:72}, rcb:{posX:62,posY:75}, lcb:{posX:38,posY:75}, lb:{posX:15,posY:72}, rm:{posX:70,posY:52}, cm:{posX:50,posY:55}, lm:{posX:30,posY:52}, rw:{posX:80,posY:28}, st:{posX:50,posY:22}, lw:{posX:20,posY:28} };

export const EXTRA_TEAMS: ScoutTeamData[] = [
  // ═══ UEFA (4 remaining: Croatia, Scotland already in base? No. Need: Croatia, Switzerland, Scotland, Austria, Norway, Bosnia, Sweden, Czech Republic, Turkey) ═══
  // Already in base: France, Angleterre, Espagne, Portugal, Allemagne, Pays-Bas, Belgique
  // Need 9 more UEFA: Croatia, Switzerland, Scotland, Austria, Norway, Bosnia, Sweden, Czech Republic, Turkey

  { pays:"Croatie", drapeau:"🇭🇷", formation:"4-3-3", joueurs:[
    {nom:"Livaković",club:"Fenerbahçe",poste:P.GK,...pos.gk},{nom:"Stanišić",club:"Bayer Leverkusen",poste:P.DEF,...pos.rb},{nom:"Gvardiol",club:"Manchester City",poste:P.DEF,...pos.rcb},{nom:"Šutalo",club:"Ajax",poste:P.DEF,...pos.lcb},{nom:"Sosa",club:"Torino",poste:P.DEF,...pos.lb},{nom:"Modrić",club:"Real Madrid",poste:P.MID,...pos.rm},{nom:"Brozović",club:"Al-Nassr",poste:P.MID,...pos.cm},{nom:"Kovačić",club:"Manchester City",poste:P.MID,...pos.lm},{nom:"Kramarić",club:"Hoffenheim",poste:P.FWD,...pos.rw},{nom:"Budimir",club:"Osasuna",poste:P.FWD,...pos.st},{nom:"Perišić",club:"Hajduk Split",poste:P.FWD,...pos.lw}]},

  { pays:"Suisse", drapeau:"🇨🇭", formation:"4-3-3", joueurs:[
    {nom:"Sommer",club:"Inter Milan",poste:P.GK,...pos.gk},{nom:"Widmer",club:"Mayence",poste:P.DEF,...pos.rb},{nom:"Akanji",club:"Manchester City",poste:P.DEF,...pos.rcb},{nom:"Elvedi",club:"B. Mönchengladbach",poste:P.DEF,...pos.lcb},{nom:"Rodriguez",club:"Torino",poste:P.DEF,...pos.lb},{nom:"Freuler",club:"Bologna",poste:P.MID,...pos.rm},{nom:"Xhaka",club:"Bayer Leverkusen",poste:P.MID,...pos.cm},{nom:"Aebischer",club:"Bologna",poste:P.MID,...pos.lm},{nom:"Shaqiri",club:"Bâle",poste:P.FWD,...pos.rw},{nom:"Embolo",club:"AS Monaco",poste:P.FWD,...pos.st},{nom:"Ndoye",club:"Bologna",poste:P.FWD,...pos.lw}]},

  { pays:"Écosse", drapeau:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", formation:"4-3-3", joueurs:[
    {nom:"Gunn",club:"Norwich",poste:P.GK,...pos.gk},{nom:"Ralston",club:"Celtic",poste:P.DEF,...pos.rb},{nom:"Hendry",club:"Al-Ettifaq",poste:P.DEF,...pos.rcb},{nom:"Hanley",club:"Norwich",poste:P.DEF,...pos.lcb},{nom:"Robertson",club:"Liverpool",poste:P.DEF,...pos.lb},{nom:"McGregor",club:"Celtic",poste:P.MID,...pos.rm},{nom:"Gilmour",club:"Napoli",poste:P.MID,...pos.cm},{nom:"McGinn",club:"Aston Villa",poste:P.MID,...pos.lm},{nom:"Adams",club:"Torino",poste:P.FWD,...pos.rw},{nom:"Dykes",club:"QPR",poste:P.FWD,...pos.st},{nom:"Christie",club:"Bournemouth",poste:P.FWD,...pos.lw}]},

  { pays:"Autriche", drapeau:"🇦🇹", formation:"4-3-3", joueurs:[
    {nom:"Pentz",club:"Bröndby",poste:P.GK,...pos.gk},{nom:"Posch",club:"Bologna",poste:P.DEF,...pos.rb},{nom:"Danso",club:"Lens",poste:P.DEF,...pos.rcb},{nom:"Wöber",club:"Leeds",poste:P.DEF,...pos.lcb},{nom:"Mwene",club:"Mayence",poste:P.DEF,...pos.lb},{nom:"Seiwald",club:"RB Leipzig",poste:P.MID,...pos.rm},{nom:"Laimer",club:"Bayern Munich",poste:P.MID,...pos.cm},{nom:"Sabitzer",club:"Borussia Dortmund",poste:P.MID,...pos.lm},{nom:"Wimmer",club:"Wolfsburg",poste:P.FWD,...pos.rw},{nom:"Arnautović",club:"Inter Milan",poste:P.FWD,...pos.st},{nom:"Baumgartner",club:"RB Leipzig",poste:P.FWD,...pos.lw}]},

  { pays:"Norvège", drapeau:"🇳🇴", formation:"4-3-3", joueurs:[
    {nom:"Nyland",club:"Sevilla",poste:P.GK,...pos.gk},{nom:"Ryerson",club:"Borussia Dortmund",poste:P.DEF,...pos.rb},{nom:"Ostigard",club:"Rennes",poste:P.DEF,...pos.rcb},{nom:"Hanche-Olsen",club:"Gent",poste:P.DEF,...pos.lcb},{nom:"Meling",club:"Rennes",poste:P.DEF,...pos.lb},{nom:"Ödegaard",club:"Arsenal",poste:P.MID,...pos.rm},{nom:"Berge",club:"Fulham",poste:P.MID,...pos.cm},{nom:"Thorstvedt",club:"Sassuolo",poste:P.MID,...pos.lm},{nom:"Nusa",club:"RB Leipzig",poste:P.FWD,...pos.rw},{nom:"Haaland",club:"Manchester City",poste:P.FWD,...pos.st},{nom:"Sörloth",club:"Atlético Madrid",poste:P.FWD,...pos.lw}]},

  { pays:"Bosnie-Herzégovine", drapeau:"🇧🇦", formation:"4-3-3", joueurs:[
    {nom:"Vasilj",club:"St. Pauli",poste:P.GK,...pos.gk},{nom:"Gazibegović",club:"Sturm Graz",poste:P.DEF,...pos.rb},{nom:"Ahmedhodžić",club:"Sheffield United",poste:P.DEF,...pos.rcb},{nom:"Katic",club:"Zurich",poste:P.DEF,...pos.lcb},{nom:"Kolašinac",club:"Atalanta",poste:P.DEF,...pos.lb},{nom:"Pjanić",club:"Sharjah FC",poste:P.MID,...pos.rm},{nom:"Hadžiahmetović",club:"Trabzonspor",poste:P.MID,...pos.cm},{nom:"Hajradinović",club:"Grasshoppers",poste:P.MID,...pos.lm},{nom:"Demirović",club:"VfB Stuttgart",poste:P.FWD,...pos.rw},{nom:"Džeko",club:"Fenerbahçe",poste:P.FWD,...pos.st},{nom:"Kololli",club:"Lugano",poste:P.FWD,...pos.lw}]},

  { pays:"Suède", drapeau:"🇸🇪", formation:"4-3-3", joueurs:[
    {nom:"Johnsson",club:"Copenhague",poste:P.GK,...pos.gk},{nom:"Krafth",club:"Newcastle",poste:P.DEF,...pos.rb},{nom:"Starfelt",club:"Celta Vigo",poste:P.DEF,...pos.rcb},{nom:"Lindelöf",club:"Manchester United",poste:P.DEF,...pos.lcb},{nom:"Augustinsson",club:"Anderlecht",poste:P.DEF,...pos.lb},{nom:"Kulusevski",club:"Tottenham",poste:P.MID,...pos.rm},{nom:"Svanberg",club:"Wolfsburg",poste:P.MID,...pos.cm},{nom:"Forsberg",club:"New York Red Bulls",poste:P.MID,...pos.lm},{nom:"Elanga",club:"Nottingham Forest",poste:P.FWD,...pos.rw},{nom:"Isak",club:"Newcastle",poste:P.FWD,...pos.st},{nom:"Gyökeres",club:"Sporting CP",poste:P.FWD,...pos.lw}]},

  { pays:"République tchèque", drapeau:"🇨🇿", formation:"4-3-3", joueurs:[
    {nom:"Staněk",club:"Slavia Prague",poste:P.GK,...pos.gk},{nom:"Coufal",club:"West Ham",poste:P.DEF,...pos.rb},{nom:"Zima",club:"Slavia Prague",poste:P.DEF,...pos.rcb},{nom:"Hranáč",club:"Hoffenheim",poste:P.DEF,...pos.lcb},{nom:"Zelený",club:"Slavia Prague",poste:P.DEF,...pos.lb},{nom:"Souček",club:"West Ham",poste:P.MID,...pos.rm},{nom:"Provod",club:"Slavia Prague",poste:P.MID,...pos.cm},{nom:"Červ",club:"Wolfsburg",poste:P.MID,...pos.lm},{nom:"Hložek",club:"Bayer Leverkusen",poste:P.FWD,...pos.rw},{nom:"Schick",club:"Bayer Leverkusen",poste:P.FWD,...pos.st},{nom:"Barák",club:"Fiorentina",poste:P.FWD,...pos.lw}]},

  { pays:"Turquie", drapeau:"🇹🇷", formation:"4-3-3", joueurs:[
    {nom:"Günok",club:"Beşiktaş",poste:P.GK,...pos.gk},{nom:"Çelik",club:"Atlético Madrid",poste:P.DEF,...pos.rb},{nom:"Demiral",club:"Al-Ahli",poste:P.DEF,...pos.rcb},{nom:"Kabak",club:"Hoffenheim",poste:P.DEF,...pos.lcb},{nom:"Kadıoğlu",club:"Brighton",poste:P.DEF,...pos.lb},{nom:"Çalhanoğlu",club:"Inter Milan",poste:P.MID,...pos.rm},{nom:"Kökçü",club:"Benfica",poste:P.MID,...pos.cm},{nom:"Yazıcı",club:"Lille",poste:P.MID,...pos.lm},{nom:"Ünder",club:"Fenerbahçe",poste:P.FWD,...pos.rw},{nom:"Yılmaz",club:"Galatasaray",poste:P.FWD,...pos.st},{nom:"Aktürkoğlu",club:"Benfica",poste:P.FWD,...pos.lw}]},

  // ═══ CONMEBOL (5 remaining: Argentina, Brazil already in base) ═══
  { pays:"Uruguay", drapeau:"🇺🇾", formation:"4-3-3", joueurs:[
    {nom:"Rochet",club:"Inter Milan",poste:P.GK,...pos.gk},{nom:"Nández",club:"Al-Ain",poste:P.DEF,...pos.rb},{nom:"Giménez",club:"Atlético Madrid",poste:P.DEF,...pos.rcb},{nom:"Araújo",club:"FC Barcelone",poste:P.DEF,...pos.lcb},{nom:"Olivera",club:"Napoli",poste:P.DEF,...pos.lb},{nom:"Valverde",club:"Real Madrid",poste:P.MID,...pos.rm},{nom:"Bentancur",club:"Tottenham",poste:P.MID,...pos.cm},{nom:"Ugarte",club:"Manchester United",poste:P.MID,...pos.lm},{nom:"Pellistri",club:"Manchester United",poste:P.FWD,...pos.rw},{nom:"Núñez",club:"Liverpool",poste:P.FWD,...pos.st},{nom:"De Arrascaeta",club:"Flamengo",poste:P.FWD,...pos.lw}]},

  { pays:"Colombie", drapeau:"🇨🇴", formation:"4-3-3", joueurs:[
    {nom:"Vargas",club:"Atlético Nacional",poste:P.GK,...pos.gk},{nom:"Muñoz",club:"Crystal Palace",poste:P.DEF,...pos.rb},{nom:"Sánchez",club:"West Ham",poste:P.DEF,...pos.rcb},{nom:"Lucumí",club:"Bologna",poste:P.DEF,...pos.lcb},{nom:"Mojica",club:"Villarreal",poste:P.DEF,...pos.lb},{nom:"Ríos",club:"Liverpool",poste:P.MID,...pos.rm},{nom:"Lerma",club:"Crystal Palace",poste:P.MID,...pos.cm},{nom:"J. Arias",club:"Flamengo",poste:P.MID,...pos.lm},{nom:"Díaz",club:"Liverpool",poste:P.FWD,...pos.rw},{nom:"Córdoba",club:"Krasnodar",poste:P.FWD,...pos.st},{nom:"Durán",club:"Aston Villa",poste:P.FWD,...pos.lw}]},

  { pays:"Équateur", drapeau:"🇪🇨", formation:"4-3-3", joueurs:[
    {nom:"Domínguez",club:"Cerro Porteño",poste:P.GK,...pos.gk},{nom:"Preciado",club:"Sparta Prague",poste:P.DEF,...pos.rb},{nom:"Torres",club:"Galatasaray",poste:P.DEF,...pos.rcb},{nom:"Hincapié",club:"Bayer Leverkusen",poste:P.DEF,...pos.lcb},{nom:"Estupiñán",club:"Brighton",poste:P.DEF,...pos.lb},{nom:"Caicedo",club:"Chelsea",poste:P.MID,...pos.rm},{nom:"Franco",club:"Cruz Azul",poste:P.MID,...pos.cm},{nom:"Páez",club:"Independiente",poste:P.MID,...pos.lm},{nom:"Plata",club:"Valladolid",poste:P.FWD,...pos.rw},{nom:"Valencia",club:"Inter Miami",poste:P.FWD,...pos.st},{nom:"Sarmiento",club:"Brighton",poste:P.FWD,...pos.lw}]},

  { pays:"Paraguay", drapeau:"🇵🇾", formation:"4-3-3", joueurs:[
    {nom:"R. Fernández",club:"Cerro Porteño",poste:P.GK,...pos.gk},{nom:"R. Rojas",club:"Inter Miami",poste:P.DEF,...pos.rb},{nom:"G. Gómez",club:"River Plate",poste:P.DEF,...pos.rcb},{nom:"Balbuena",club:"Dynamo Moscou",poste:P.DEF,...pos.lcb},{nom:"Alderete",club:"Getafe",poste:P.DEF,...pos.lb},{nom:"Cubas",club:"Montpellier",poste:P.MID,...pos.rm},{nom:"Villasanti",club:"Grêmio",poste:P.MID,...pos.cm},{nom:"Almirón",club:"Newcastle",poste:P.MID,...pos.lm},{nom:"Enciso",club:"Brighton",poste:P.FWD,...pos.rw},{nom:"Sanabria",club:"Torino",poste:P.FWD,...pos.st},{nom:"Romero",club:"Corinthians",poste:P.FWD,...pos.lw}]},

  // ═══ CONCACAF (3 remaining: USA, Canada, Mexico already in base) ═══
  { pays:"Panama", drapeau:"🇵🇦", formation:"4-3-3", joueurs:[
    {nom:"Mosquera",club:"Independiente Medellín",poste:P.GK,...pos.gk},{nom:"Murillo",club:"Anderlecht",poste:P.DEF,...pos.rb},{nom:"Córdoba A.",club:"Krasnodar",poste:P.DEF,...pos.rcb},{nom:"Farina",club:"Universitario",poste:P.DEF,...pos.lcb},{nom:"Davis",club:"Fuenlabrada",poste:P.DEF,...pos.lb},{nom:"Carrasquilla",club:"Houston Dynamo",poste:P.MID,...pos.rm},{nom:"Godoy",club:"Olimpia",poste:P.MID,...pos.cm},{nom:"Blackburn",club:"Columbus Crew",poste:P.MID,...pos.lm},{nom:"Fajardo",club:"Alajuelense",poste:P.FWD,...pos.rw},{nom:"Bárcenas",club:"Club América",poste:P.FWD,...pos.st},{nom:"Murillo M.",club:"Anderlecht",poste:P.FWD,...pos.lw}]},

  { pays:"Curaçao", drapeau:"🇨🇼", formation:"4-3-3", joueurs:[
    {nom:"Room",club:"PSV Eindhoven",poste:P.GK,...pos.gk},{nom:"Martina",club:"Feyenoord",poste:P.DEF,...pos.rb},{nom:"Van Anholt",club:"PSV Eindhoven",poste:P.DEF,...pos.rcb},{nom:"St. Jago",club:"Austin FC",poste:P.DEF,...pos.lcb},{nom:"Quansah",club:"Queens Park Rangers",poste:P.DEF,...pos.lb},{nom:"Bacuna",club:"Groningen",poste:P.MID,...pos.rm},{nom:"Méndes",club:"AZ Alkmaar",poste:P.MID,...pos.cm},{nom:"Dos Santos",club:"FC Twente",poste:P.MID,...pos.lm},{nom:"Hooi",club:"Beitar Jerusalem",poste:P.FWD,...pos.rw},{nom:"Hato",club:"Ajax",poste:P.FWD,...pos.st},{nom:"Nepomuceno",club:"Al-Arabi",poste:P.FWD,...pos.lw}]},

  { pays:"Haïti", drapeau:"🇭🇹", formation:"4-3-3", joueurs:[
    {nom:"Duval",club:"Inter Miami",poste:P.GK,...pos.gk},{nom:"Jérôme",club:"Austria Vienne",poste:P.DEF,...pos.rb},{nom:"Pierrot",club:"Louisville City",poste:P.DEF,...pos.rcb},{nom:"André",club:"Caen",poste:P.DEF,...pos.lcb},{nom:"Bossé",club:"Grenoble",poste:P.DEF,...pos.lb},{nom:"Alcénat",club:"Nîmes",poste:P.MID,...pos.rm},{nom:"Gédéon",club:"Le Havre",poste:P.MID,...pos.cm},{nom:"Lotiès",club:"Guingamp",poste:P.MID,...pos.lm},{nom:"Bonhomme",club:"USL Championship",poste:P.FWD,...pos.rw},{nom:"Bassong",club:"Nashville SC",poste:P.FWD,...pos.st},{nom:"Milord",club:"Fort Lauderdale",poste:P.FWD,...pos.lw}]},

  { pays:"Mexique", drapeau:"🇲🇽", formation:"4-3-3", joueurs:[
    {nom:"Ochoa",club:"Salernitana",poste:P.GK,...pos.gk},{nom:"J. Sánchez",club:"Ajax",poste:P.DEF,...pos.rb},{nom:"Montes",club:"Benfica",poste:P.DEF,...pos.rcb},{nom:"Vásquez",club:"Genoa",poste:P.DEF,...pos.lcb},{nom:"Gallardo",club:"Toluca",poste:P.DEF,...pos.lb},{nom:"Álvarez",club:"West Ham",poste:P.MID,...pos.rm},{nom:"Romo",club:"Monterrey",poste:P.MID,...pos.cm},{nom:"Pineda",club:"AEK Athens",poste:P.MID,...pos.lm},{nom:"Lozano",club:"San Diego FC",poste:P.FWD,...pos.rw},{nom:"Giménez",club:"Feyenoord",poste:P.FWD,...pos.st},{nom:"Vega",club:"Toluca",poste:P.FWD,...pos.lw}]},

  { pays:"Canada", drapeau:"🇨🇦", formation:"4-3-3", joueurs:[
    {nom:"Crépeau",club:"Portland",poste:P.GK,...pos.gk},{nom:"Johnston",club:"Celtic",poste:P.DEF,...pos.rb},{nom:"Bombito",club:"Colorado",poste:P.DEF,...pos.rcb},{nom:"Cornelius",club:"Malmö",poste:P.DEF,...pos.lcb},{nom:"Davies",club:"Bayern Munich",poste:P.DEF,...pos.lb},{nom:"Eustáquio",club:"Porto",poste:P.MID,...pos.rm},{nom:"Koné",club:"Watford",poste:P.MID,...pos.cm},{nom:"Buchanan",club:"Inter Milan",poste:P.MID,...pos.lm},{nom:"David",club:"Lille",poste:P.FWD,...pos.rw},{nom:"Larin",club:"Vallecano",poste:P.FWD,...pos.st},{nom:"Shaffelburg",club:"Nashville",poste:P.FWD,...pos.lw}]},

  // ═══ CAF - Afrique (9 remaining: Morocco already in base) ═══
  { pays:"Sénégal", drapeau:"🇸🇳", formation:"4-3-3", joueurs:[
    {nom:"E. Mendy",club:"Al-Ahli",poste:P.GK,...pos.gk},{nom:"Sabaly",club:"Real Betis",poste:P.DEF,...pos.rb},{nom:"Koulibaly",club:"Al-Hilal",poste:P.DEF,...pos.rcb},{nom:"Diallo",club:"Al-Ahli",poste:P.DEF,...pos.lcb},{nom:"Jakobs",club:"AS Monaco",poste:P.DEF,...pos.lb},{nom:"P. Gueye",club:"Villarreal",poste:P.MID,...pos.rm},{nom:"N. Mendy",club:"Leicester",poste:P.MID,...pos.cm},{nom:"Diatta",club:"AS Monaco",poste:P.MID,...pos.lm},{nom:"Sarr",club:"Crystal Palace",poste:P.FWD,...pos.rw},{nom:"Jackson",club:"Chelsea",poste:P.FWD,...pos.st},{nom:"Dia",club:"Lazio",poste:P.FWD,...pos.lw}]},

  { pays:"Égypte", drapeau:"🇪🇬", formation:"4-3-3", joueurs:[
    {nom:"El-Shenawy",club:"Al Ahly",poste:P.GK,...pos.gk},{nom:"Ashour",club:"Al Ahly",poste:P.DEF,...pos.rb},{nom:"Hegazi",club:"Al-Ittihad",poste:P.DEF,...pos.rcb},{nom:"Abdelmonem",club:"Besiktas",poste:P.DEF,...pos.lcb},{nom:"Fatouh",club:"Zamalek",poste:P.DEF,...pos.lb},{nom:"Elneny",club:"Al Jazira",poste:P.MID,...pos.rm},{nom:"Fathi",club:"Al Ahly",poste:P.MID,...pos.cm},{nom:"Trezeguet",club:"Trabzonspor",poste:P.MID,...pos.lm},{nom:"M. Salah",club:"Liverpool",poste:P.FWD,...pos.rw},{nom:"Marmoush",club:"Manchester City",poste:P.FWD,...pos.st},{nom:"Adel",club:"Pyramids FC",poste:P.FWD,...pos.lw}]},

  { pays:"Algérie", drapeau:"🇩🇿", formation:"4-3-3", joueurs:[
    {nom:"Mandréa",club:"Lens",poste:P.GK,...pos.gk},{nom:"Atal",club:"Nice",poste:P.DEF,...pos.rb},{nom:"Mandi",club:"Villarreal",poste:P.DEF,...pos.rcb},{nom:"Bedrane",club:"Espérance Tunis",poste:P.DEF,...pos.lcb},{nom:"Bensebaini",club:"Borussia Dortmund",poste:P.DEF,...pos.lb},{nom:"Bennacer",club:"AC Milan",poste:P.MID,...pos.rm},{nom:"Zerrouki",club:"Feyenoord",poste:P.MID,...pos.cm},{nom:"Aouar",club:"Al-Ittihad",poste:P.MID,...pos.lm},{nom:"Mahrez",club:"Al-Ahli",poste:P.FWD,...pos.rw},{nom:"Bounedjah",club:"Al-Sadd",poste:P.FWD,...pos.st},{nom:"Amine Gouiri",club:"Rennes",poste:P.FWD,...pos.lw}]},

  { pays:"Tunisie", drapeau:"🇹🇳", formation:"4-3-3", joueurs:[
    {nom:"Dahmen",club:"Montpellier",poste:P.GK,...pos.gk},{nom:"Drager",club:"Bâle",poste:P.DEF,...pos.rb},{nom:"Bronn",club:"Salernitana",poste:P.DEF,...pos.rcb},{nom:"Meriah",club:"Espérance Tunis",poste:P.DEF,...pos.lcb},{nom:"Abdi",club:"Caen",poste:P.DEF,...pos.lb},{nom:"Laidouni",club:"Union Berlin",poste:P.MID,...pos.rm},{nom:"Skhiri",club:"Francfort",poste:P.MID,...pos.cm},{nom:"Mejbri",club:"Burnley",poste:P.MID,...pos.lm},{nom:"Msakni",club:"Al-Arabi",poste:P.FWD,...pos.rw},{nom:"Khenissi",club:"Étoile du Sahel",poste:P.FWD,...pos.st},{nom:"Jaziri",club:"Zamalek",poste:P.FWD,...pos.lw}]},

  { pays:"Afrique du Sud", drapeau:"🇿🇦", formation:"4-3-3", joueurs:[
    {nom:"Williams",club:"Mamelodi Sundowns",poste:P.GK,...pos.gk},{nom:"Mudau",club:"Mamelodi Sundowns",poste:P.DEF,...pos.rb},{nom:"De Reuck",club:"Mamelodi Sundowns",poste:P.DEF,...pos.rcb},{nom:"Kekana",club:"Mamelodi Sundowns",poste:P.DEF,...pos.lcb},{nom:"Mashego",club:"Cape Town City",poste:P.DEF,...pos.lb},{nom:"Mokoena",club:"Mamelodi Sundowns",poste:P.MID,...pos.rm},{nom:"Tau",club:"Al Ahly",poste:P.MID,...pos.cm},{nom:"Mokwena",club:"Mamelodi Sundowns",poste:P.MID,...pos.lm},{nom:"Zwane",club:"Mamelodi Sundowns",poste:P.FWD,...pos.rw},{nom:"Shalulile",club:"Mamelodi Sundowns",poste:P.FWD,...pos.st},{nom:"Foster",club:"Burnley",poste:P.FWD,...pos.lw}]},

  { pays:"Côte d'Ivoire", drapeau:"🇨🇮", formation:"4-3-3", joueurs:[
    {nom:"Y. Fofana",club:"Lens",poste:P.GK,...pos.gk},{nom:"Aurier",club:"Galatasaray",poste:P.DEF,...pos.rb},{nom:"Deli",club:"Hatayspor",poste:P.DEF,...pos.rcb},{nom:"Badiashile",club:"Chelsea",poste:P.DEF,...pos.lcb},{nom:"Boly",club:"Nantes",poste:P.DEF,...pos.lb},{nom:"Seri",club:"Hull City",poste:P.MID,...pos.rm},{nom:"Kessié",club:"Al-Ahli",poste:P.MID,...pos.cm},{nom:"Pepe",club:"Villarreal",poste:P.MID,...pos.lm},{nom:"Gradel",club:"Sivasspor",poste:P.FWD,...pos.rw},{nom:"Haller",club:"Borussia Dortmund",poste:P.FWD,...pos.st},{nom:"Boga",club:"Nice",poste:P.FWD,...pos.lw}]},

  { pays:"Cap-Vert", drapeau:"🇨🇻", formation:"4-3-3", joueurs:[
    {nom:"Vozinha",club:"Gil Vicente",poste:P.GK,...pos.gk},{nom:"Stopira",club:"Académica",poste:P.DEF,...pos.rb},{nom:"Borges",club:"Arouca",poste:P.DEF,...pos.rcb},{nom:"Diogo",club:"Le Havre",poste:P.DEF,...pos.lcb},{nom:"Tavares",club:"Moreirense",poste:P.DEF,...pos.lb},{nom:"Kenny",club:"Desportivo Aves",poste:P.MID,...pos.rm},{nom:"Dias",club:"Estoril",poste:P.MID,...pos.cm},{nom:"Nuno Santos",club:"Boavista",poste:P.MID,...pos.lm},{nom:"Garry Rodrigues",club:"Olympiakos",poste:P.FWD,...pos.rw},{nom:"Beltrame",club:"Académica",poste:P.FWD,...pos.st},{nom:"Hélio",club:"Nacional",poste:P.FWD,...pos.lw}]},

  { pays:"Ghana", drapeau:"🇬🇭", formation:"4-3-3", joueurs:[
    {nom:"Zigi",club:"St. Gallen",poste:P.GK,...pos.gk},{nom:"Lamptey",club:"Brighton",poste:P.DEF,...pos.rb},{nom:"Salisu",club:"AS Monaco",poste:P.DEF,...pos.rcb},{nom:"Amartey",club:"Leicester",poste:P.DEF,...pos.lcb},{nom:"Mensah",club:"Auxerre",poste:P.DEF,...pos.lb},{nom:"Partey",club:"Arsenal",poste:P.MID,...pos.rm},{nom:"Kudus",club:"West Ham",poste:P.MID,...pos.cm},{nom:"Samed",club:"Lens",poste:P.MID,...pos.lm},{nom:"Gyasi",club:"Cagliari",poste:P.FWD,...pos.rw},{nom:"Inaki Williams",club:"Athletic Bilbao",poste:P.FWD,...pos.st},{nom:"Ayew",club:"Le Havre",poste:P.FWD,...pos.lw}]},

  { pays:"RD Congo", drapeau:"🇨🇩", formation:"4-3-3", joueurs:[
    {nom:"Kiassumbua",club:"STVV",poste:P.GK,...pos.gk},{nom:"Mbemba",club:"OM",poste:P.DEF,...pos.rb},{nom:"Luyindama",club:"Galatasaray",poste:P.DEF,...pos.rcb},{nom:"Masuaku",club:"Beşiktaş",poste:P.DEF,...pos.lcb},{nom:"Ngoma",club:"TP Mazembe",poste:P.DEF,...pos.lb},{nom:"Kakuta",club:"Lens",poste:P.MID,...pos.rm},{nom:"Moutoussamy",club:"Nantes",poste:P.MID,...pos.cm},{nom:"Wissa",club:"Brentford",poste:P.MID,...pos.lm},{nom:"Bakambu",club:"Olympiakos",poste:P.FWD,...pos.rw},{nom:"Batshuayi",club:"Galatasaray",poste:P.FWD,...pos.st},{nom:"Mpoku",club:"Al-Wahda",poste:P.FWD,...pos.lw}]},

  // ═══ AFC - Asie (7 remaining: Japan already in base) ═══
  { pays:"Iran", drapeau:"🇮🇷", formation:"4-3-3", joueurs:[
    {nom:"Beiranvand",club:"Persépolis",poste:P.GK,...pos.gk},{nom:"Moharrami",club:"Dinamo Zagreb",poste:P.DEF,...pos.rb},{nom:"Hosseini",club:"Kayserispor",poste:P.DEF,...pos.rcb},{nom:"Kanaani",club:"Copenhague",poste:P.DEF,...pos.lcb},{nom:"Mohammadi",club:"AEK Athens",poste:P.DEF,...pos.lb},{nom:"Noorollahi",club:"Persépolis",poste:P.MID,...pos.rm},{nom:"Ezatolahi",club:"Vejle",poste:P.MID,...pos.cm},{nom:"Jahanbakhsh",club:"Feyenoord",poste:P.MID,...pos.lm},{nom:"Azmoun",club:"AS Roma",poste:P.FWD,...pos.rw},{nom:"Taremi",club:"Inter Milan",poste:P.FWD,...pos.st},{nom:"Ghoddos",club:"Brentford",poste:P.FWD,...pos.lw}]},

  { pays:"Corée du Sud", drapeau:"🇰🇷", formation:"4-3-3", joueurs:[
    {nom:"Kim S.",club:"Wolverhampton",poste:P.GK,...pos.gk},{nom:"Kim M.",club:"Fenerbahçe",poste:P.DEF,...pos.rb},{nom:"Kim J.",club:"Bayern Munich",poste:P.DEF,...pos.rcb},{nom:"Kim Y.",club:"Napoli",poste:P.DEF,...pos.lcb},{nom:"Hong",club:"Gamba Osaka",poste:P.DEF,...pos.lb},{nom:"Lee J.",club:"PSG",poste:P.MID,...pos.rm},{nom:"Hwang I.",club:"Red Bull Salzbourg",poste:P.MID,...pos.cm},{nom:"Lee K.",club:"PSG",poste:P.MID,...pos.lm},{nom:"Hwang H.",club:"Wolverhampton",poste:P.FWD,...pos.rw},{nom:"Son H.",club:"Tottenham",poste:P.FWD,...pos.st},{nom:"Cho G.",club:"Wolverhampton",poste:P.FWD,...pos.lw}]},

  { pays:"Australie", drapeau:"🇦🇺", formation:"4-3-3", joueurs:[
    {nom:"Ryan",club:"AS Roma",poste:P.GK,...pos.gk},{nom:"Atkinson",club:"Aston Villa",poste:P.DEF,...pos.rb},{nom:"Souttar",club:"Sheffield United",poste:P.DEF,...pos.rcb},{nom:"Rowles",club:"Hearts",poste:P.DEF,...pos.lcb},{nom:"Behich",club:"Dundee United",poste:P.DEF,...pos.lb},{nom:"Mooy",club:"Shanghai Port",poste:P.MID,...pos.rm},{nom:"Irvine",club:"St Pauli",poste:P.MID,...pos.cm},{nom:"McGree",club:"Middlesbrough",poste:P.MID,...pos.lm},{nom:"Borrello",club:"Macarthur FC",poste:P.FWD,...pos.rw},{nom:"Duke",club:"Yokohama Marinos",poste:P.FWD,...pos.st},{nom:"Leckie",club:"Melbourne City",poste:P.FWD,...pos.lw}]},

  { pays:"Arabie Saoudite", drapeau:"🇸🇦", formation:"4-3-3", joueurs:[
    {nom:"Al-Owais",club:"Al-Hilal",poste:P.GK,...pos.gk},{nom:"Abdulhamid",club:"Villarreal",poste:P.DEF,...pos.rb},{nom:"Al-Amri",club:"Al-Ahli",poste:P.DEF,...pos.rcb},{nom:"Al-Bulayhi",club:"Al-Hilal",poste:P.DEF,...pos.lcb},{nom:"Boushal",club:"Al-Shabab",poste:P.DEF,...pos.lb},{nom:"Kanno",club:"Al-Hilal",poste:P.MID,...pos.rm},{nom:"Al-Malki",club:"Al-Hilal",poste:P.MID,...pos.cm},{nom:"Al-Dawsari",club:"Al-Hilal",poste:P.MID,...pos.lm},{nom:"Al-Shehri",club:"Al-Hilal",poste:P.FWD,...pos.rw},{nom:"Al-Buraikan",club:"Al-Hilal",poste:P.FWD,...pos.st},{nom:"Bahebri",club:"Al-Ittihad",poste:P.FWD,...pos.lw}]},

  { pays:"Ouzbékistan", drapeau:"🇺🇿", formation:"4-3-3", joueurs:[
    {nom:"Nesterov",club:"Pakhtakor",poste:P.GK,...pos.gk},{nom:"Yaxshiboev",club:"AGMK",poste:P.DEF,...pos.rb},{nom:"Komilov",club:"Pakhtakor",poste:P.DEF,...pos.rcb},{nom:"Aliqulov",club:"Bunyodkor",poste:P.DEF,...pos.lcb},{nom:"Kholmatov",club:"Nasaf",poste:P.DEF,...pos.lb},{nom:"Fayzullaev",club:"Lens",poste:P.MID,...pos.rm},{nom:"Tukhtasinov",club:"Pakhtakor",poste:P.MID,...pos.cm},{nom:"Siddikov",club:"Bunyodkor",poste:P.MID,...pos.lm},{nom:"Shomurodov",club:"AS Roma",poste:P.FWD,...pos.rw},{nom:"Jaloliddinov",club:"Pakhtakor",poste:P.FWD,...pos.st},{nom:"Urunov",club:"Lokomotiv Tashkent",poste:P.FWD,...pos.lw}]},

  { pays:"Jordanie", drapeau:"🇯🇴", formation:"4-3-3", joueurs:[
    {nom:"Shafi",club:"Al-Wehdat",poste:P.GK,...pos.gk},{nom:"Haddad",club:"Al-Faisaly",poste:P.DEF,...pos.rb},{nom:"Salman",club:"Al-Raed",poste:P.DEF,...pos.rcb},{nom:"Al-Tamari",club:"Montpellier",poste:P.DEF,...pos.lcb},{nom:"Zahran",club:"Al-Ahli",poste:P.DEF,...pos.lb},{nom:"Al-Dardour",club:"Al-Faisaly",poste:P.MID,...pos.rm},{nom:"Bani Ateyah",club:"Al-Wehdat",poste:P.MID,...pos.cm},{nom:"Rawshdeh",club:"Al-Wehdat",poste:P.MID,...pos.lm},{nom:"Al-Taamari",club:"Montpellier",poste:P.FWD,...pos.rw},{nom:"Hammad",club:"Al-Faisaly",poste:P.FWD,...pos.st},{nom:"Abu Hammad",club:"Al-Salt",poste:P.FWD,...pos.lw}]},

  { pays:"Qatar", drapeau:"🇶🇦", formation:"4-3-3", joueurs:[
    {nom:"Barsham",club:"Al-Sadd",poste:P.GK,...pos.gk},{nom:"Pedro Miguel",club:"Al-Sadd",poste:P.DEF,...pos.rb},{nom:"Al-Rawi",club:"Al-Rayyan",poste:P.DEF,...pos.rcb},{nom:"Hassan",club:"Al-Gharafa",poste:P.DEF,...pos.lcb},{nom:"Ahmed",club:"Al-Sadd",poste:P.DEF,...pos.lb},{nom:"Boudiaf",club:"Al-Duhail",poste:P.MID,...pos.rm},{nom:"Al-Haydos",club:"Al-Sadd",poste:P.MID,...pos.cm},{nom:"Madibo",club:"Al-Duhail",poste:P.MID,...pos.lm},{nom:"Afif",club:"Al-Sadd",poste:P.FWD,...pos.rw},{nom:"Ali",club:"Al-Duhail",poste:P.FWD,...pos.st},{nom:"Muntari",club:"Al-Duhail",poste:P.FWD,...pos.lw}]},

  { pays:"Irak", drapeau:"🇮🇶", formation:"4-3-3", joueurs:[
    {nom:"Al-Talib",club:"Al-Shorta",poste:P.GK,...pos.gk},{nom:"Al-Hamadani",club:"Al-Quwa Al-Jawiya",poste:P.DEF,...pos.rb},{nom:"Ibrahim",club:"Malmö",poste:P.DEF,...pos.rcb},{nom:"Adnan",club:"Ume\u00e5",poste:P.DEF,...pos.lcb},{nom:"Ali Faez",club:"Al-Zawraa",poste:P.DEF,...pos.lb},{nom:"Attwan",club:"Al-Quwa Al-Jawiya",poste:P.MID,...pos.rm},{nom:"Tahseen",club:"Al-Shorta",poste:P.MID,...pos.cm},{nom:"Aymen Hussein",club:"Persépolis",poste:P.MID,...pos.lm},{nom:"Mohanad Ali",club:"Al-Arabi",poste:P.FWD,...pos.rw},{nom:"Al-Mandhar",club:"Al-Zawraa",poste:P.FWD,...pos.st},{nom:"Amjad Attwan",club:"Al-Shorta",poste:P.FWD,...pos.lw}]},

  // ═══ OFC - Océanie (1 team) ═══
  { pays:"Nouvelle-Zélande", drapeau:"🇳🇿", formation:"4-3-3", joueurs:[
    {nom:"Sail",club:"Orlando City",poste:P.GK,...pos.gk},{nom:"Payne",club:"Adelaide United",poste:P.DEF,...pos.rb},{nom:"Tuiloma",club:"Vancouver Whitecaps",poste:P.DEF,...pos.rcb},{nom:"Boxall",club:"Nashville SC",poste:P.DEF,...pos.lcb},{nom:"Cacace",club:"Empoli",poste:P.DEF,...pos.lb},{nom:"Bell",club:"Viking FK",poste:P.MID,...pos.rm},{nom:"Stamenic",club:"Rapid Vienne",poste:P.MID,...pos.cm},{nom:"Singh",club:"PSV Eindhoven",poste:P.MID,...pos.lm},{nom:"Waine",club:"San Diego FC",poste:P.FWD,...pos.rw},{nom:"Wood",club:"Burnley",poste:P.FWD,...pos.st},{nom:"Thomas",club:"Auckland FC",poste:P.FWD,...pos.lw}]},
];
