/**
 * FootQuest - Foot Trivia game data
 * Questions UNIQUEMENT sur les Coupes du Monde FIFA (1930-2022)
 */

export interface TriviaQuestionData {
  question: string;
  reponses: string[];
  bonneReponse: number; // index 0-3
  categorie: "histoire" | "records" | "finales" | "buteurs" | "pays_hotes";
  difficulte: "facile" | "moyen" | "difficile";
  points: number;
}

export const TRIVIA_QUESTIONS: TriviaQuestionData[] = [
  // ═══════════════════════════════════════════
  // FACILE (20 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel pays a remporté la Coupe du Monde 2022 au Qatar ?",
    reponses: ["France", "Argentine", "Brésil", "Croatie"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a remporté le plus de Coupes du Monde ?",
    reponses: ["Allemagne", "Italie", "Brésil", "Argentine"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "En quelle année a eu lieu la première Coupe du Monde ?",
    reponses: ["1928", "1930", "1934", "1926"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a accueilli la Coupe du Monde 2018 ?",
    reponses: ["Brésil", "Allemagne", "Russie", "Qatar"],
    bonneReponse: 2,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui est le meilleur buteur de l'histoire des Coupes du Monde ?",
    reponses: ["Ronaldo", "Miroslav Klose", "Pelé", "Messi"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien d'étoiles le Brésil a-t-il sur son maillot ?",
    reponses: ["3", "4", "5", "6"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a organisé la CDM 2014 ?",
    reponses: ["Argentine", "Brésil", "Afrique du Sud", "Russie"],
    bonneReponse: 1,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quelle équipe a perdu la finale de la CDM 2022 ?",
    reponses: ["Brésil", "France", "Croatie", "Maroc"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays africain a atteint les demi-finales de la CDM 2022 ?",
    reponses: ["Sénégal", "Ghana", "Cameroun", "Maroc"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui a marqué le 'but de la main de Dieu' en CDM 1986 ?",
    reponses: ["Pelé", "Maradona", "Zidane", "Platini"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien de pays participeront à la CDM 2026 ?",
    reponses: ["32", "40", "48", "64"],
    bonneReponse: 2,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quels pays co-organisent la CDM 2026 ?",
    reponses: ["USA, Mexique, Canada", "USA, Mexique, Brésil", "USA, Canada, Angleterre", "Mexique, Canada, Argentine"],
    bonneReponse: 0,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a gagné la première Coupe du Monde en 1930 ?",
    reponses: ["Argentine", "Brésil", "Uruguay", "Italie"],
    bonneReponse: 2,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien de Coupes du Monde la France a-t-elle remportées ?",
    reponses: ["1", "2", "3", "4"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel joueur a inscrit un triplé en finale de la CDM 2022 ?",
    reponses: ["Messi", "Mbappé", "Di María", "Griezmann"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "L'Allemagne a subi une défaite 7-1 dans quelle CDM ?",
    reponses: ["CDM 2010", "CDM 2014", "CDM 2018", "CDM 2006"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel continent n'a jamais remporté de Coupe du Monde ?",
    reponses: ["Afrique", "Asie", "Les deux", "Aucun des deux"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quelle équipe a été éliminée par le Brésil 7-1 en demi-finale CDM 2014 ?",
    reponses: ["Argentine", "France", "Brésil", "Aucune, c'est le Brésil qui a perdu"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui a gagné le Ballon d'Or de la CDM 2022 ?",
    reponses: ["Mbappé", "Messi", "Modric", "Griezmann"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "En quelle année la France a-t-elle gagné sa première CDM ?",
    reponses: ["1994", "1998", "2002", "2006"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },

  // ═══════════════════════════════════════════
  // MOYEN (20 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel joueur détient le record de buts en une seule CDM (13 buts) ?",
    reponses: ["Miroslav Klose", "Just Fontaine", "Gerd Müller", "Ronaldo"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a accueilli la CDM 2010 ?",
    reponses: ["Brésil", "Allemagne", "Afrique du Sud", "Corée/Japon"],
    bonneReponse: 2,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Qui a inscrit le but en or en finale de la CDM 2002 (Brésil vs Allemagne) ?",
    reponses: ["Rivaldo", "Ronaldo", "Ronaldinho", "Cafu"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a gagné les CDM 2006 ?",
    reponses: ["France", "Italie", "Allemagne", "Brésil"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de buts Miroslav Klose a-t-il marqué en CDM au total ?",
    reponses: ["14", "15", "16", "18"],
    bonneReponse: 2,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle est la seule CDM avec une finale décidée par un match de barrage ?",
    reponses: ["CDM 1950", "CDM 1930", "CDM 1934", "CDM 1958"],
    bonneReponse: 0,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a été le premier à remporter deux CDM consécutives ?",
    reponses: ["Brésil", "Italie", "Uruguay", "Allemagne"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "En quelle année Pelé a-t-il remporté sa première Coupe du Monde ?",
    reponses: ["1954", "1958", "1962", "1966"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel célèbre coup de tête a marqué la finale CDM 2006 ?",
    reponses: ["Zidane sur Buffon", "Zidane sur Materazzi", "Henry sur Cannavaro", "Trezeguet sur le poteau"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe asiatique a atteint les demi-finales de la CDM 2002 ?",
    reponses: ["Japon", "Corée du Sud", "Chine", "Arabie Saoudite"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de fois l'Argentine a-t-elle remporté la Coupe du Monde ?",
    reponses: ["1", "2", "3", "4"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel gardien a arrêté les tirs au but en finale CDM 2022 pour l'Argentine ?",
    reponses: ["Rulli", "E. Martínez", "Armani", "Romero"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a accueilli la CDM en 1998 ?",
    reponses: ["Angleterre", "Allemagne", "Espagne", "France"],
    bonneReponse: 3,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de buts Messi a-t-il inscrits en CDM 2022 ?",
    reponses: ["5", "7", "8", "6"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe a remporté la CDM 2010 en Afrique du Sud ?",
    reponses: ["Pays-Bas", "Allemagne", "Espagne", "Brésil"],
    bonneReponse: 2,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "En quelle année la CDM a-t-elle été organisée en Asie pour la première fois ?",
    reponses: ["1998", "2002", "2006", "2010"],
    bonneReponse: 1,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel joueur a marqué le but le plus rapide en CDM (11 secondes) ?",
    reponses: ["Hakan Şükür", "Miroslav Klose", "Ronaldo", "Clint Dempsey"],
    bonneReponse: 0,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe africaine a été la première à atteindre les quarts de finale ?",
    reponses: ["Nigeria", "Cameroun", "Ghana", "Sénégal"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de CDM l'Allemagne a-t-elle remportées ?",
    reponses: ["3", "4", "5", "2"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a perdu deux finales de CDM consécutives en 2014 et 2018 ?",
    reponses: ["France", "Argentine", "Croatie", "Aucun"],
    bonneReponse: 3,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },

  // ═══════════════════════════════════════════
  // DIFFICILE (10 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel joueur a participé à 5 Coupes du Monde différentes ?",
    reponses: ["Lothar Matthäus", "Messi", "Cristiano Ronaldo", "Les trois"],
    bonneReponse: 3,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a remporté la CDM 1950 dans un format de poule finale (pas de finale) ?",
    reponses: ["Brésil", "Uruguay", "Italie", "Suède"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel est le score le plus large dans l'histoire de la CDM ?",
    reponses: ["9-0 (Hongrie vs Corée du Sud 1954)", "10-1 (Hongrie vs El Salvador 1982)", "9-0 (Yougoslavie vs Zaïre 1974)", "7-1 (Allemagne vs Brésil 2014)"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a gagné la CDM sans jamais perdre un match en phase finale (imbattu) en 1978 ?",
    reponses: ["Argentine", "Brésil", "Allemagne", "Italie"],
    bonneReponse: 0,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Qui est le plus jeune buteur de l'histoire des finales de CDM ?",
    reponses: ["Pelé", "Mbappé", "Ronaldo", "Owen"],
    bonneReponse: 0,
    categorie: "buteurs",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a été éliminé en phase de groupes de toutes les CDM entre 2006 et 2018 ?",
    reponses: ["Italie", "France", "Angleterre", "Aucun"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Combien de finales de CDM se sont décidées aux tirs au but ?",
    reponses: ["2", "3", "4", "1"],
    bonneReponse: 0,
    categorie: "finales",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel gardien a reçu le Ballon d'Or de la CDM 2002 ?",
    reponses: ["Buffon", "Oliver Kahn", "Rüstü Reçber", "Marcos"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel match est surnommé le 'Miracle de Berne' en CDM ?",
    reponses: ["Finale 1950 (Uruguay vs Brésil)", "Finale 1954 (Allemagne vs Hongrie)", "Demi-finale 1970 (Italie vs Allemagne)", "Finale 1966 (Angleterre vs Allemagne)"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Dans quelle ville se jouera la finale de la CDM 2026 ?",
    reponses: ["New York", "Los Angeles", "Mexico", "MetLife Stadium (New Jersey)"],
    bonneReponse: 3,
    categorie: "pays_hotes",
    difficulte: "difficile",
    points: 30,
  },
  // 30 NOUVELLES QUESTIONS FACILES
  { question: "Quel pays a remporté la Coupe du Monde 2018 ?", reponses: ["France", "Croatie", "Brésil", "Belgique"], bonneReponse: 0, categorie: "finales", difficulte: "facile", points: 10 },
  { question: "Dans quel pays s'est déroulée la CDM 1998 ?", reponses: ["Brésil", "France", "Corée du Sud", "Italie"], bonneReponse: 1, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Quelle est la couleur du maillot de l'équipe des Pays-Bas ?", reponses: ["Bleu", "Blanc", "Orange", "Vert"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Combien d'équipes participaient à chaque Coupe du Monde entre 1998 et 2022 ?", reponses: ["24", "32", "48", "16"], bonneReponse: 1, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Qui est le meilleur buteur de l'Équipe de France en CDM ?", reponses: ["Zidane", "Henry", "Giroud", "Fontaine"], bonneReponse: 3, categorie: "buteurs", difficulte: "facile", points: 10 },
  { question: "Dans quel pays s'est jouée la Coupe du Monde 2006 ?", reponses: ["France", "Allemagne", "Italie", "Japon"], bonneReponse: 1, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Quelle équipe africaine a les 'Lions Indomptables' comme surnom ?", reponses: ["Sénégal", "Nigeria", "Cameroun", "Côte d'Ivoire"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Quelle sélection est appelée la 'Seleção' ?", reponses: ["Portugal", "Mexique", "Brésil", "Argentine"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Quel joueur est appelé 'El Pibe de Oro' ?", reponses: ["Maradona", "Messi", "Ronaldinho", "Zidane"], bonneReponse: 0, categorie: "records", difficulte: "facile", points: 10 },
  { question: "Quelle équipe européenne a remporté la CDM 2014 ?", reponses: ["Espagne", "Allemagne", "France", "Italie"], bonneReponse: 1, categorie: "finales", difficulte: "facile", points: 10 },
  { question: "Combien de fois la France a organisé la Coupe du Monde ?", reponses: ["1", "2", "3", "0"], bonneReponse: 1, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Qui était le capitaine de la France lors de la finale CDM 1998 ?", reponses: ["Zidane", "Blanc", "Deschamps", "Desailly"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Quelle équipe a été battue par l'Espagne en finale CDM 2010 ?", reponses: ["Allemagne", "Uruguay", "Pays-Bas", "Brésil"], bonneReponse: 2, categorie: "finales", difficulte: "facile", points: 10 },
  { question: "Quel est le surnom de la sélection d'Uruguay ?", reponses: ["La Celeste", "La Roja", "El Tri", "Les Diables Rouges"], bonneReponse: 0, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "De quelle couleur sont les maillots traditionnels de l'Italie ?", reponses: ["Rouge", "Blanc", "Vert", "Bleu"], bonneReponse: 3, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Dans quelle ville s'est jouée la finale de la CDM 1998 ?", reponses: ["Lyon", "Marseille", "Saint-Denis", "Paris"], bonneReponse: 2, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Quel pays asiatique a déjà accueilli la CDM avec un autre pays ?", reponses: ["Japon (et Corée)", "Chine (et Japon)", "Iran (et Irak)", "Arabie Saoudite (et Qatar)"], bonneReponse: 0, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Pour quel pays a joué Cristiano Ronaldo en CDM ?", reponses: ["Brésil", "Espagne", "Portugal", "Italie"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Quelle équipe est surnommée 'La Roja' ?", reponses: ["Argentine", "Mexique", "Espagne", "Belgique"], bonneReponse: 2, categorie: "histoire", difficulte: "facile", points: 10 },
  { question: "Quelle ancienne gloire brésilienne était surnommée 'Il Fenomeno' ?", reponses: ["Pelé", "Rivaldo", "Ronaldo", "Neymar"], bonneReponse: 2, categorie: "buteurs", difficulte: "facile", points: 10 },
  { question: "Quel pays organise la CDM en 1994 ?", reponses: ["Mexique", "USA", "France", "Italie"], bonneReponse: 1, categorie: "pays_hotes", difficulte: "facile", points: 10 },
  { question: "Quel ancien joueur a remporté la CDM à la fois en tant que joueur puis entraîneur (comme Didier Deschamps) ?", reponses: ["Zidane", "Maradona", "Beckenbauer", "Cruyff"], bonneReponse: 2, categorie: "records", difficulte: "facile", points: 10 },
  { question: "Combien d'étoiles a l'Argentine sur son maillot officiel aujourd'hui ?", reponses: ["1", "2", "3", "4"], bonneReponse: 2, categorie: "records", difficulte: "facile", points: 10 },
  { question: "À qui l'équipe de France a-t-elle remporté sa première CDM ?", reponses: ["Italie", "Brésil", "Croatie", "Allemagne"], bonneReponse: 1, categorie: "finales", difficulte: "facile", points: 10 },
  { question: "Quelle est la particularité climatique ayant changé la date de la CDM 2022 ?", reponses: ["Tornades", "Forte Chaleur", "Neige", "Pluies Moussons"], bonneReponse: 1, categorie: "pays_hotes", difficulte: "facile", points: 10 },

  // 30 NOUVELLES QUESTIONS MOYENNES
  { question: "Quel pays a remporté la Coupe du Monde en Espagne en 1982 ?", reponses: ["RFA (Allemagne)", "Italie", "Argentine", "Brésil"], bonneReponse: 1, categorie: "finales", difficulte: "moyen", points: 20 },
  { question: "Qui est le meilleur buteur français lors d'une seule phase finale de CDM avec 13 buts ?", reponses: ["Thierry Henry", "Kylian Mbappé", "Just Fontaine", "Michel Platini"], bonneReponse: 2, categorie: "records", difficulte: "moyen", points: 20 },
  { question: "Quelle équipe britannique a gagné la CDM en 1966 ?", reponses: ["Écosse", "Pays de Galles", "Angleterre", "Irlande du Nord"], bonneReponse: 2, categorie: "finales", difficulte: "moyen", points: 20 },
  { question: "Quel pays a éliminé le Brésil en 1/4 de finale lors de la CDM 2006 (1-0, but d'Henry) ?", reponses: ["Portugal", "France", "Italie", "Allemagne"], bonneReponse: 1, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Lors de quelle Coupe du Monde l'Italie a-t-elle été éliminée au premier tour en 2010 ?", reponses: ["Afrique du Sud", "Brésil", "Russie", "Qatar"], bonneReponse: 0, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "De quel club provenaient la majorité des joueurs espagnols vainqueurs en 2010 ?", reponses: ["Real Madrid", "Athletic Bilbao", "FC Barcelone", "Valence"], bonneReponse: 2, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Dans quel pays Diego Maradona a-t-il été contrôlé positif à l'éphédrine (CDM) ?", reponses: ["1986 au Mexique", "1990 en Italie", "1994 aux USA", "1982 en Espagne"], bonneReponse: 2, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Qui a gagné le Golden Boot (Soulier d'Or) de la CDM 2018 en Russie ?", reponses: ["Antoine Griezmann", "Harry Kane", "Kylian Mbappé", "Luka Modric"], bonneReponse: 1, categorie: "buteurs", difficulte: "moyen", points: 20 },
  { question: "Quel petit pays européen s'est qualifié pour la première fois en 2016 et y a cru jusqu'aux 1/4 ?", reponses: ["Islande (Euro mais pas CDM)", "Islande a fait la CDM 2018", "Pays de Galles", "Panama"], bonneReponse: 1, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Quelle équipe a été la surprise en atteignant les 1/2 finales en 2002 aux côtés du Brésil et de l'Allemagne ?", reponses: ["Sénégal et Japon", "Corée du Sud et Turquie", "USA et Espagne", "Mexique et Italie"], bonneReponse: 1, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Quelle est l'équipe africaine surnommée les 'Black Stars' ?", reponses: ["Sénégal", "Nigeria", "Cameroun", "Ghana"], bonneReponse: 3, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Combien d'équipes africaines participaient au premier tour en 1998 ?", reponses: ["4", "5", "6", "3"], bonneReponse: 1, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Qui a raté son pénalty crucial pour l'Italie en finale CDM 1994 face au Brésil ?", reponses: ["Baresi", "Roberto Baggio", "Maldini", "Albertini"], bonneReponse: 1, categorie: "finales", difficulte: "moyen", points: 20 },
  { question: "Quelles sont les mascottes mémorables 'Footix', 'Fuleco' et 'Zabivaka' ? Respectivement de...", reponses: ["France 98, Brésil 2014, Russie 2018", "Russie 2018, Brésil 2014, Qatar 2022", "France 98, Japon 2002, AFS 2010", "Aucun des trois"], bonneReponse: 0, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Quel pays d'Amérique du Sud n'a jamais franchi le premier tour d'une CDM ?", reponses: ["Venezuela", "Bolivie", "Équateur", "Pérou"], bonneReponse: 0, categorie: "histoire", difficulte: "moyen", points: 20 },
  { question: "Quel pays européen est le seul organisateur à n'avoir jamais passé la phase de groupes en tant que pays hôte ?", reponses: ["Suisse (1954)", "Afrique du Sud (C'est pas en Europe)", "Aucun", "Aucun"], bonneReponse: 2, categorie: "records", difficulte: "moyen", points: 20 },
  { question: "Qui est le meilleur buteur colombien lors de la Coupe du Monde 2014 ?", reponses: ["Radamel Falcao", "James Rodríguez", "Juan Cuadrado", "Carlos Bacca"], bonneReponse: 1, categorie: "buteurs", difficulte: "moyen", points: 20 },
  { question: "Quel joueur est célèbre pour son but 'Incroyable' en 1/8eme de CDM 1998 contre l'Argentine ?", reponses: ["David Beckham", "Michael Owen", "Alan Shearer", "Paul Scholes"], bonneReponse: 1, categorie: "buteurs", difficulte: "moyen", points: 20 },
  { question: "Quelle a été la particularité de la finale de 2010 (Pays-Bas vs Espagne) ?", reponses: ["Plus grand nombre de cartons en finale", "La plus rapide à se conclure", "Zéro carton jaune", "Des arrêts exclusifs sur penalty"], bonneReponse: 0, categorie: "records", difficulte: "moyen", points: 20 },
  { question: "Quel pays (à l'époque sous un autre nom) a atteint la finale en 1974 et 1978 sans la gagner ?", reponses: ["Tchécoslovaquie", "URSS", "Pays-Bas", "Yougoslavie"], bonneReponse: 2, categorie: "histoire", difficulte: "moyen", points: 20 },

  // 15 NOUVELLES QUESTIONS DIFFICILES
  { question: "Quel joueur italien a remporté la CDM à l'âge de 40 ans en tant que capitaine (Record du plus vieux joueur à soulever la coupe) ?", reponses: ["Gianluigi Buffon", "Dino Zoff", "Paolo Maldini", "Fabio Cannavaro"], bonneReponse: 1, categorie: "records", difficulte: "difficile", points: 30 },
  { question: "Quel buteur a planté un triplé en Finale 1966 pour l'Angleterre ?", reponses: ["Geoff Hurst", "Bobby Moore", "Bobby Charlton", "Gordon Banks"], bonneReponse: 0, categorie: "records", difficulte: "difficile", points: 30 },
  { question: "Quel gardien a été élu meilleur joueur d'une Coupe du Monde, une première historique en 2002 ?", reponses: ["Fabien Barthez", "Oliver Kahn", "Gianluigi Buffon", "Iker Casillas"], bonneReponse: 1, categorie: "records", difficulte: "difficile", points: 30 },
  { question: "Quelle équipe a fini 3ème de la Coupe du Monde sans jamais perdre un match ou être dominée aux tab en 2006 ? Piège : Une équipe à fini 3ème invaincue ?", reponses: ["Non, c'était l'Italie en 1990", "Non, l'Allemagne a perdu en 1/2 en 2006", "En vérité, l'Italie est la seule invaincue en 2006 (Gagnante)", "Suisse éliminée sans encaisser de but en 2006 (en 1/8)"], bonneReponse: 3, categorie: "records", difficulte: "difficile", points: 30 },
  { question: "Lors du 'Drame de Séville' (France-RFA 1982), qui a marqué le fameux 3ème but français lors des prolongations (qui faisait 3-1) ?", reponses: ["Alain Giresse", "Michel Platini", "Marius Trésor", "Dominique Rocheteau"], bonneReponse: 0, categorie: "buteurs", difficulte: "difficile", points: 30 },
  { question: "L'Inde s'est qualifiée pour la CDM 1950, mais s'est retirée en invoquant les frais de voyage, et une autre raison de légende. Laquelle ?", reponses: ["La FIFA a interdit de jouer pieds nus", "Il y avait en Russie une épidémie", "Ils refusaient de rencontrer l'Angleterre", "Par peur de l'altitude au Brésil"], bonneReponse: 0, categorie: "histoire", difficulte: "difficile", points: 30 },
  { question: "Parmi les 22 joueurs espagnols sacrés en 2010, un seul évoluait hors d'Espagne. De qui s'agissait-il ?", reponses: ["Cesc Fàbregas (Arsenal)", "Fernando Torres (Liverpool)", "Pepe Reina (Liverpool)", "Les trois évoluaient en Angleterre"], bonneReponse: 3, categorie: "histoire", difficulte: "difficile", points: 30 },
  { question: "Quelle équipe détient le record funeste du plus grand nombre de Coupes du Monde terminées à la deuxième place ?", reponses: ["Allemagne", "Argentine", "Pays-Bas", "Hongrie"], bonneReponse: 0, categorie: "records", difficulte: "difficile", points: 30 },
  { question: "Quel attaquant brésilien n'a pas été sélectionné pour la CDM 2002 malgré la pression de tout le pays ?", reponses: ["Romario", "Giovane Élber", "Mário Jardel", "Bebeto"], bonneReponse: 0, categorie: "histoire", difficulte: "difficile", points: 30 },
  { question: "Lequel de ces entraîneurs a remporté la Coupe du Monde avec son pays tout en révolutionnant le football de son époque, en 1978 ?", reponses: ["Rinus Michels", "César Luis Menotti", "Mário Zagallo", "Enzo Bearzot"], bonneReponse: 1, categorie: "histoire", difficulte: "difficile", points: 30 }
];
