/**
 * FootQuest - Foot Trivia game data
 * Questions UNIQUEMENT sur les Coupes du Monde FIFA (1930-2022)
 */

export interface TriviaQuestionData {
  question: string;
  reponses: string[];
  bonneReponse: number; // index 0-3
  categorie: "histoire" | "records" | "finales" | "buteurs" | "pays_hotes";
  difficulte: "facile" | "moyen" | "difficile";
  points: number;
}

export const TRIVIA_QUESTIONS: TriviaQuestionData[] = [
  // ═══════════════════════════════════════════
  // FACILE (20 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel pays a remporté la Coupe du Monde 2022 au Qatar ?",
    reponses: ["France", "Argentine", "Brésil", "Croatie"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a remporté le plus de Coupes du Monde ?",
    reponses: ["Allemagne", "Italie", "Brésil", "Argentine"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "En quelle année a eu lieu la première Coupe du Monde ?",
    reponses: ["1928", "1930", "1934", "1926"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a accueilli la Coupe du Monde 2018 ?",
    reponses: ["Brésil", "Allemagne", "Russie", "Qatar"],
    bonneReponse: 2,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui est le meilleur buteur de l'histoire des Coupes du Monde ?",
    reponses: ["Ronaldo", "Miroslav Klose", "Pelé", "Messi"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien d'étoiles le Brésil a-t-il sur son maillot ?",
    reponses: ["3", "4", "5", "6"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a organisé la CDM 2014 ?",
    reponses: ["Argentine", "Brésil", "Afrique du Sud", "Russie"],
    bonneReponse: 1,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quelle équipe a perdu la finale de la CDM 2022 ?",
    reponses: ["Brésil", "France", "Croatie", "Maroc"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays africain a atteint les demi-finales de la CDM 2022 ?",
    reponses: ["Sénégal", "Ghana", "Cameroun", "Maroc"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui a marqué le 'but de la main de Dieu' en CDM 1986 ?",
    reponses: ["Pelé", "Maradona", "Zidane", "Platini"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien de pays participeront à la CDM 2026 ?",
    reponses: ["32", "40", "48", "64"],
    bonneReponse: 2,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quels pays co-organisent la CDM 2026 ?",
    reponses: ["USA, Mexique, Canada", "USA, Mexique, Brésil", "USA, Canada, Angleterre", "Mexique, Canada, Argentine"],
    bonneReponse: 0,
    categorie: "pays_hotes",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel pays a gagné la première Coupe du Monde en 1930 ?",
    reponses: ["Argentine", "Brésil", "Uruguay", "Italie"],
    bonneReponse: 2,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Combien de Coupes du Monde la France a-t-elle remportées ?",
    reponses: ["1", "2", "3", "4"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel joueur a inscrit un triplé en finale de la CDM 2022 ?",
    reponses: ["Messi", "Mbappé", "Di María", "Griezmann"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "L'Allemagne a subi une défaite 7-1 dans quelle CDM ?",
    reponses: ["CDM 2010", "CDM 2014", "CDM 2018", "CDM 2006"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quel continent n'a jamais remporté de Coupe du Monde ?",
    reponses: ["Afrique", "Asie", "Les deux", "Aucun des deux"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Quelle équipe a été éliminée par le Brésil 7-1 en demi-finale CDM 2014 ?",
    reponses: ["Argentine", "France", "Brésil", "Aucune, c'est le Brésil qui a perdu"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "Qui a gagné le Ballon d'Or de la CDM 2022 ?",
    reponses: ["Mbappé", "Messi", "Modric", "Griezmann"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "facile",
    points: 10,
  },
  {
    question: "En quelle année la France a-t-elle gagné sa première CDM ?",
    reponses: ["1994", "1998", "2002", "2006"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "facile",
    points: 10,
  },

  // ═══════════════════════════════════════════
  // MOYEN (20 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel joueur détient le record de buts en une seule CDM (13 buts) ?",
    reponses: ["Miroslav Klose", "Just Fontaine", "Gerd Müller", "Ronaldo"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a accueilli la CDM 2010 ?",
    reponses: ["Brésil", "Allemagne", "Afrique du Sud", "Corée/Japon"],
    bonneReponse: 2,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Qui a inscrit le but en or en finale de la CDM 2002 (Brésil vs Allemagne) ?",
    reponses: ["Rivaldo", "Ronaldo", "Ronaldinho", "Cafu"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a gagné les CDM 2006 ?",
    reponses: ["France", "Italie", "Allemagne", "Brésil"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de buts Miroslav Klose a-t-il marqué en CDM au total ?",
    reponses: ["14", "15", "16", "18"],
    bonneReponse: 2,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle est la seule CDM avec une finale décidée par un match de barrage ?",
    reponses: ["CDM 1950", "CDM 1930", "CDM 1934", "CDM 1958"],
    bonneReponse: 0,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a été le premier à remporter deux CDM consécutives ?",
    reponses: ["Brésil", "Italie", "Uruguay", "Allemagne"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "En quelle année Pelé a-t-il remporté sa première Coupe du Monde ?",
    reponses: ["1954", "1958", "1962", "1966"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel célèbre coup de tête a marqué la finale CDM 2006 ?",
    reponses: ["Zidane sur Buffon", "Zidane sur Materazzi", "Henry sur Cannavaro", "Trezeguet sur le poteau"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe asiatique a atteint les demi-finales de la CDM 2002 ?",
    reponses: ["Japon", "Corée du Sud", "Chine", "Arabie Saoudite"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de fois l'Argentine a-t-elle remporté la Coupe du Monde ?",
    reponses: ["1", "2", "3", "4"],
    bonneReponse: 2,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel gardien a arrêté les tirs au but en finale CDM 2022 pour l'Argentine ?",
    reponses: ["Rulli", "E. Martínez", "Armani", "Romero"],
    bonneReponse: 1,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a accueilli la CDM en 1998 ?",
    reponses: ["Angleterre", "Allemagne", "Espagne", "France"],
    bonneReponse: 3,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de buts Messi a-t-il inscrits en CDM 2022 ?",
    reponses: ["5", "7", "8", "6"],
    bonneReponse: 1,
    categorie: "buteurs",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe a remporté la CDM 2010 en Afrique du Sud ?",
    reponses: ["Pays-Bas", "Allemagne", "Espagne", "Brésil"],
    bonneReponse: 2,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "En quelle année la CDM a-t-elle été organisée en Asie pour la première fois ?",
    reponses: ["1998", "2002", "2006", "2010"],
    bonneReponse: 1,
    categorie: "pays_hotes",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel joueur a marqué le but le plus rapide en CDM (11 secondes) ?",
    reponses: ["Hakan Şükür", "Miroslav Klose", "Ronaldo", "Clint Dempsey"],
    bonneReponse: 0,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quelle équipe africaine a été la première à atteindre les quarts de finale ?",
    reponses: ["Nigeria", "Cameroun", "Ghana", "Sénégal"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Combien de CDM l'Allemagne a-t-elle remportées ?",
    reponses: ["3", "4", "5", "2"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "moyen",
    points: 20,
  },
  {
    question: "Quel pays a perdu deux finales de CDM consécutives en 2014 et 2018 ?",
    reponses: ["France", "Argentine", "Croatie", "Aucun"],
    bonneReponse: 3,
    categorie: "finales",
    difficulte: "moyen",
    points: 20,
  },

  // ═══════════════════════════════════════════
  // DIFFICILE (10 questions)
  // ═══════════════════════════════════════════
  {
    question: "Quel joueur a participé à 5 Coupes du Monde différentes ?",
    reponses: ["Lothar Matthäus", "Messi", "Cristiano Ronaldo", "Les trois"],
    bonneReponse: 3,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a remporté la CDM 1950 dans un format de poule finale (pas de finale) ?",
    reponses: ["Brésil", "Uruguay", "Italie", "Suède"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel est le score le plus large dans l'histoire de la CDM ?",
    reponses: ["9-0 (Hongrie vs Corée du Sud 1954)", "10-1 (Hongrie vs El Salvador 1982)", "9-0 (Yougoslavie vs Zaïre 1974)", "7-1 (Allemagne vs Brésil 2014)"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a gagné la CDM sans jamais perdre un match en phase finale (imbattu) en 1978 ?",
    reponses: ["Argentine", "Brésil", "Allemagne", "Italie"],
    bonneReponse: 0,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Qui est le plus jeune buteur de l'histoire des finales de CDM ?",
    reponses: ["Pelé", "Mbappé", "Ronaldo", "Owen"],
    bonneReponse: 0,
    categorie: "buteurs",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel pays a été éliminé en phase de groupes de toutes les CDM entre 2006 et 2018 ?",
    reponses: ["Italie", "France", "Angleterre", "Aucun"],
    bonneReponse: 3,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Combien de finales de CDM se sont décidées aux tirs au but ?",
    reponses: ["2", "3", "4", "1"],
    bonneReponse: 0,
    categorie: "finales",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel gardien a reçu le Ballon d'Or de la CDM 2002 ?",
    reponses: ["Buffon", "Oliver Kahn", "Rüstü Reçber", "Marcos"],
    bonneReponse: 1,
    categorie: "records",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Quel match est surnommé le 'Miracle de Berne' en CDM ?",
    reponses: ["Finale 1950 (Uruguay vs Brésil)", "Finale 1954 (Allemagne vs Hongrie)", "Demi-finale 1970 (Italie vs Allemagne)", "Finale 1966 (Angleterre vs Allemagne)"],
    bonneReponse: 1,
    categorie: "histoire",
    difficulte: "difficile",
    points: 30,
  },
  {
    question: "Dans quelle ville se jouera la finale de la CDM 2026 ?",
    reponses: ["New York", "Los Angeles", "Mexico", "MetLife Stadium (New Jersey)"],
    bonneReponse: 3,
    categorie: "pays_hotes",
    difficulte: "difficile",
    points: 30,
  },
];
